** -*- koshu -*-
**
**  <版権表示>
**    このデータセットは以下の著作物を改変して作成しています。
**    新潟市オープンデータ、新潟市、クリエイティブ・コモンズ・ライセンス 表示 2.1 日本
**    (CC-BY 2.1 JP) http://creativecommons.org/licenses/by/2.1/jp/
**

|-- META  /data 'od-bandaibashi001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-bandaibashi/od-bandaibashi001.html"
|-- META  /data 'od-bandaibashi001  /name 'タイトル  /content '萬代橋とチューリップ
|-- META  /data 'od-bandaibashi001  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-bandaibashi001  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-bandaibashi001  /name '公表組織名  /content '新潟市

|-- META  /data 'od-bandaibashi001  /name '地域  /content '新潟市中央区万代
|-- META  /data 'od-bandaibashi001  /name '実効画像サイズ  /content "幅2000×高さ3008（ピクセル）"
|-- META  /data 'od-bandaibashi001  /name '撮影日  /content '2005年4月
|-- META  /data 'od-bandaibashi001  /name '更新頻度  /content '不定期
|-- META  /data 'od-bandaibashi001  /name "言語・文字コード"  /content "日本語・UTF-8"

|-- META  /data 'od-bandaibashi002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-bandaibashi/od-bandaibashi002.html"
|-- META  /data 'od-bandaibashi002  /name 'タイトル  /content '萬代橋と信濃川1
|-- META  /data 'od-bandaibashi002  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-bandaibashi002  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-bandaibashi002  /name '公表組織名  /content '新潟市

|-- META  /data 'od-bandaibashi002  /name '地域  /content '新潟市中央区下大川前通
|-- META  /data 'od-bandaibashi002  /name '実効画像サイズ  /content "幅4928×高さ3264（ピクセル）"
|-- META  /data 'od-bandaibashi002  /name '撮影日  /content '2013年
|-- META  /data 'od-bandaibashi002  /name '更新頻度  /content '不定期
|-- META  /data 'od-bandaibashi002  /name "言語・文字コード"  /content "日本語・UTF-8"

|-- META  /data 'od-bandaibashi003  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-bandaibashi/od-bandaibashi003.html"
|-- META  /data 'od-bandaibashi003  /name 'タイトル  /content '萬代橋と信濃川2
|-- META  /data 'od-bandaibashi003  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-bandaibashi003  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-bandaibashi003  /name '公表組織名  /content '新潟市
*** 25

|-- META  /data 'od-bandaibashi003  /name '地域  /content '新潟市中央区万代
|-- META  /data 'od-bandaibashi003  /name '実効画像サイズ  /content "幅4224×高さ2798（ピクセル）"
|-- META  /data 'od-bandaibashi003  /name '撮影日  /content '2013年
|-- META  /data 'od-bandaibashi003  /name '更新頻度  /content '不定期
|-- META  /data 'od-bandaibashi003  /name "言語・文字コード"  /content "日本語・UTF-8"

|-- META  /data 'od-bandaibashi004  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-bandaibashi/od-bandaibashi004.html"
|-- META  /data 'od-bandaibashi004  /name 'タイトル  /content '萬代橋の夕景
|-- META  /data 'od-bandaibashi004  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-bandaibashi004  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-bandaibashi004  /name '公表組織名  /content '新潟市

|-- META  /data 'od-bandaibashi004  /name '地域  /content '新潟市中央区万代
|-- META  /data 'od-bandaibashi004  /name '実効画像サイズ  /content "幅1378×高さ1604（ピクセル）"
|-- META  /data 'od-bandaibashi004  /name '撮影日  /content '2007年
|-- META  /data 'od-bandaibashi004  /name '更新頻度  /content '不定期
|-- META  /data 'od-bandaibashi004  /name "言語・文字コード"  /content "日本語・UTF-8"

|-- META  /data 'od-bandaibashi005  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-bandaibashi/od-bandaibashi005.html"
|-- META  /data 'od-bandaibashi005  /name 'タイトル  /content '萬代橋1
|-- META  /data 'od-bandaibashi005  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-bandaibashi005  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-bandaibashi005  /name '公表組織名  /content '新潟市

|-- META  /data 'od-bandaibashi005  /name '地域  /content '新潟市中央区万代
|-- META  /data 'od-bandaibashi005  /name '実効画像サイズ  /content "幅3072×高さ2048（ピクセル）"
|-- META  /data 'od-bandaibashi005  /name '撮影日  /content '2005年10月6日
|-- META  /data 'od-bandaibashi005  /name '撮影時刻  /content '午前7時2分
|-- META  /data 'od-bandaibashi005  /name '更新頻度  /content '不定期
*** 50

|-- META  /data 'od-bandaibashi005  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-bandaibashi006  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-bandaibashi/od-bandaibashi006.html"
|-- META  /data 'od-bandaibashi006  /name 'タイトル  /content '萬代橋2
|-- META  /data 'od-bandaibashi006  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-bandaibashi006  /name '作成者  /content "地域・魅力創造部広報課"

|-- META  /data 'od-bandaibashi006  /name '公表組織名  /content '新潟市
|-- META  /data 'od-bandaibashi006  /name '地域  /content '新潟市中央区万代
|-- META  /data 'od-bandaibashi006  /name '実効画像サイズ  /content "幅2105×高さ1400（ピクセル）"
|-- META  /data 'od-bandaibashi006  /name '撮影日  /content '2005年
|-- META  /data 'od-bandaibashi006  /name '更新頻度  /content '不定期

|-- META  /data 'od-bandaibashi006  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-bird  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-toukei/od-kankyo/od-shizenkankyo/od-bird.html"
|-- META  /data 'od-bird  /name 'タイトル  /content '環境関連施設等
|-- META  /data 'od-bird  /name 'ライセンス  /content "CC-BY（表示）"
|-- META  /data 'od-bird  /name '作成者  /content '環境部環境政策課

|-- META  /data 'od-bird  /name '使用言語  /content "日本語・UTF-8"
|-- META  /data 'od-bird  /name '公表組織名  /content '新潟市
|-- META  /data 'od-bird  /name '更新頻度  /content '毎年
|-- META  /data 'od-chosha001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-chosha/od-chosha001.html"
|-- META  /data 'od-chosha001  /name 'タイトル  /content '新潟市役所本館

|-- META  /data 'od-chosha001  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-chosha001  /name '住所  /content '新潟市中央区学校町通1番町602番地1
|-- META  /data 'od-chosha001  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-chosha001  /name '公表組織名  /content '新潟市
|-- META  /data 'od-chosha001  /name '実効画像サイズ  /content "幅4752×高さ3168（ピクセル）"
*** 75

|-- META  /data 'od-chosha001  /name '撮影日  /content '2013年7月19日
|-- META  /data 'od-chosha001  /name '撮影時刻  /content '午後1時41分
|-- META  /data 'od-chosha001  /name '更新頻度  /content '不定期
|-- META  /data 'od-chosha001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-chosha002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-chosha/od-chosha002.html"

|-- META  /data 'od-chosha002  /name 'タイトル  /content '新潟市役所分館
|-- META  /data 'od-chosha002  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-chosha002  /name '住所  /content '新潟市中央区学校町通1番町602番地1
|-- META  /data 'od-chosha002  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-chosha002  /name '公表組織名  /content '新潟市

|-- META  /data 'od-chosha002  /name '実効画像サイズ  /content "幅4752×高さ3168（ピクセル）"
|-- META  /data 'od-chosha002  /name '撮影日  /content '2013年7月19日
|-- META  /data 'od-chosha002  /name '撮影時刻  /content '午後1時11分
|-- META  /data 'od-chosha002  /name '更新頻度  /content '不定期
|-- META  /data 'od-chosha002  /name "言語・文字コード"  /content "日本語・UTF-8"

|-- META  /data 'od-chosha003  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-chosha/od-chosha003.html"
|-- META  /data 'od-chosha003  /name 'タイトル  /content "新潟市役所白山浦庁舎1号棟・5号棟"
|-- META  /data 'od-chosha003  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-chosha003  /name '住所  /content '新潟市中央区学校町通1番町602番地1
|-- META  /data 'od-chosha003  /name '作成者  /content "地域・魅力創造部広報課"

|-- META  /data 'od-chosha003  /name '公表組織名  /content '新潟市
|-- META  /data 'od-chosha003  /name '実効画像サイズ  /content "幅4752×高さ3168（ピクセル）"
|-- META  /data 'od-chosha003  /name '撮影日  /content '2013年7月19日
|-- META  /data 'od-chosha003  /name '撮影時刻  /content '午後1時23分
|-- META  /data 'od-chosha003  /name '更新頻度  /content '不定期
*** 100

|-- META  /data 'od-chosha003  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-co2  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-toukei/od-kankyo/od-ondanka/od-co2.html"
|-- META  /data 'od-co2  /name 'タイトル  /content "【二酸化炭素排出量】部門別内訳"
|-- META  /data 'od-co2  /name 'ライセンス  /content "CC-BY（表示）"
|-- META  /data 'od-co2  /name '作成者  /content '環境部環境政策課

|-- META  /data 'od-co2  /name '使用言語  /content "日本語・UTF-8"
|-- META  /data 'od-co2  /name '公表組織名  /content '新潟市
|-- META  /data 'od-co2  /name '更新頻度  /content '毎年
|-- META  /data 'od-co2  /name '補足1  /content "各年度の東北電力株式会社実排出係数に基づき算出しています。"
|-- META  /data 'od-denen001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-denen/od-denen001.html"

|-- META  /data 'od-denen001  /name 'タイトル  /content '越後平野の田園風景1
|-- META  /data 'od-denen001  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-denen001  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-denen001  /name '地域  /content '新潟市西蒲区
|-- META  /data 'od-denen001  /name '実効画像サイズ  /content "幅2582×高さ3267（ピクセル）"

|-- META  /data 'od-denen001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-denen002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-denen/od-denen002.html"
|-- META  /data 'od-denen002  /name 'タイトル  /content '越後平野の田園風景2
|-- META  /data 'od-denen002  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-denen002  /name "公表者・作成者"  /content "地域・魅力創造部広報課"

|-- META  /data 'od-denen002  /name '地域  /content '新潟市西蒲区
|-- META  /data 'od-denen002  /name '実効画像サイズ  /content "幅3888×高さ2592（ピクセル）"
|-- META  /data 'od-denen002  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-denen003  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-denen/od-denen003.html"
|-- META  /data 'od-denen003  /name 'タイトル  /content '満願寺のはさ木並木1
*** 125

|-- META  /data 'od-denen003  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-denen003  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-denen003  /name '地域  /content '新潟市秋葉区満願寺
|-- META  /data 'od-denen003  /name '実効画像サイズ  /content "幅2480×高さ1654（ピクセル）"
|-- META  /data 'od-denen003  /name "言語・文字コード"  /content "日本語・UTF-8"

|-- META  /data 'od-denen004  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-denen/od-denen004.html"
|-- META  /data 'od-denen004  /name 'タイトル  /content '夏井のはざ木
|-- META  /data 'od-denen004  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-denen004  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-denen004  /name '地域  /content '新潟市西蒲区夏井

|-- META  /data 'od-denen004  /name '実効画像サイズ  /content "幅3008×高さ2000（ピクセル）"
|-- META  /data 'od-denen004  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-denen005  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-denen/od-denen005.html"
|-- META  /data 'od-denen005  /name 'タイトル  /content '稲穂
|-- META  /data 'od-denen005  /name 'ライセンス  /content "表示（CC-BY）"

|-- META  /data 'od-denen005  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-denen005  /name '地域  /content '新潟市
|-- META  /data 'od-denen005  /name '実効画像サイズ  /content "幅3145×高さ2097（ピクセル）"
|-- META  /data 'od-denen005  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-denen006  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-denen/od-denen006.html"

|-- META  /data 'od-denen006  /name 'タイトル  /content '越後平野の田園風景3
|-- META  /data 'od-denen006  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-denen006  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-denen006  /name '地域  /content '新潟市北区前新田
|-- META  /data 'od-denen006  /name '実効画像サイズ  /content "幅5184×高さ3456（ピクセル）"
*** 150

|-- META  /data 'od-denen006  /name '撮影日  /content '2014年8月22日
|-- META  /data 'od-denen006  /name '撮影時刻  /content '午前11時48分
|-- META  /data 'od-denen006  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-denen007  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-denen/od-denen007.html"
|-- META  /data 'od-denen007  /name 'タイトル  /content '越後平野の田園風景4

|-- META  /data 'od-denen007  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-denen007  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-denen007  /name '地域  /content '新潟市西蒲区松野尾
|-- META  /data 'od-denen007  /name '実効画像サイズ  /content "幅3264×高さ2448（ピクセル）"
|-- META  /data 'od-denen007  /name '撮影日  /content '2014年9月7日

|-- META  /data 'od-denen007  /name '撮影時刻  /content '午前9時28分
|-- META  /data 'od-denen007  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-denen008  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-denen/od-denen008.html"
|-- META  /data 'od-denen008  /name 'タイトル  /content '満願寺のはさ木並木2
|-- META  /data 'od-denen008  /name 'ライセンス  /content "表示（CC-BY）"

|-- META  /data 'od-denen008  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-denen008  /name '地域  /content '新潟市秋葉区満願寺
|-- META  /data 'od-denen008  /name '実効画像サイズ  /content "幅3264×高さ2448（ピクセル）"
|-- META  /data 'od-denen008  /name '撮影日  /content '2013年9月23日
|-- META  /data 'od-denen008  /name '撮影時刻  /content '午前9時19分

|-- META  /data 'od-denen008  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-denen009  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-denen/od-denen009.html"
|-- META  /data 'od-denen009  /name 'タイトル  /content '満願寺のはさ木並木3
|-- META  /data 'od-denen009  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-denen009  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
*** 175

|-- META  /data 'od-denen009  /name '地域  /content '新潟市秋葉区満願寺
|-- META  /data 'od-denen009  /name '実効画像サイズ  /content "幅3264×高さ2448（ピクセル）"
|-- META  /data 'od-denen009  /name '撮影日  /content '2013年9月23日
|-- META  /data 'od-denen009  /name '撮影時間  /content '午前9時35分
|-- META  /data 'od-denen009  /name "言語・文字コード"  /content "日本語・UTF-8"

|-- META  /data 'od-energy  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-toukei/od-kankyo/od-ondanka/od-energy.html"
|-- META  /data 'od-energy  /name 'タイトル  /content '環境関連施設等
|-- META  /data 'od-energy  /name 'ライセンス  /content "CC-BY（表示）"
|-- META  /data 'od-energy  /name '作成者  /content '環境部環境政策課
|-- META  /data 'od-energy  /name '使用言語  /content "日本語・UTF-8"

|-- META  /data 'od-energy  /name '公表組織名  /content '新潟市
|-- META  /data 'od-energy  /name '更新頻度  /content '毎年
|-- META  /data 'od-enkikan001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-bunkashisetsu/od-enkikan/od-enkikan001.html"
|-- META  /data 'od-enkikan001  /name 'タイトル  /content '燕喜館
|-- META  /data 'od-enkikan001  /name 'ライセンス  /content "表示（CC-BY）"

|-- META  /data 'od-enkikan001  /name '住所  /content '新潟市中央区一番堀通町1番地2白山公園内
|-- META  /data 'od-enkikan001  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-enkikan001  /name '公表組織名  /content '新潟市
|-- META  /data 'od-enkikan001  /name '実効画像サイズ  /content "幅2832×高さ4256（ピクセル）"
|-- META  /data 'od-enkikan001  /name '撮影日  /content '2009年

|-- META  /data 'od-enkikan001  /name '更新頻度  /content '不定期
|-- META  /data 'od-enkikan001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-enkikan003  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-bunkashisetsu/od-enkikan/od-enkikan003.html"
|-- META  /data 'od-enkikan003  /name 'タイトル  /content '燕喜館と桜1
|-- META  /data 'od-enkikan003  /name 'ライセンス  /content "表示（CC-BY）"
*** 200

|-- META  /data 'od-enkikan003  /name '住所  /content '新潟市中央区一番堀通町1番地2白山公園内
|-- META  /data 'od-enkikan003  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-enkikan003  /name '公表組織名  /content '新潟市
|-- META  /data 'od-enkikan003  /name '実効画像サイズ  /content "幅3264×高さ2448（ピクセル）"
|-- META  /data 'od-enkikan003  /name '撮影日  /content '2014年4月15日

|-- META  /data 'od-enkikan003  /name '撮影時刻  /content '午前8時28分
|-- META  /data 'od-enkikan003  /name '更新頻度  /content '不定期
|-- META  /data 'od-enkikan003  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-enkikan004  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-bunkashisetsu/od-enkikan/od-enkikan004.html"
|-- META  /data 'od-enkikan004  /name 'タイトル  /content '燕喜館と桜2

|-- META  /data 'od-enkikan004  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-enkikan004  /name '住所  /content '新潟市中央区一番堀通町1番地2白山公園内
|-- META  /data 'od-enkikan004  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-enkikan004  /name '公表組織名  /content '新潟市
|-- META  /data 'od-enkikan004  /name '実効画像サイズ  /content "幅2496×高さ1664（ピクセル）"

|-- META  /data 'od-enkikan004  /name '撮影日  /content '2014年4月12日
|-- META  /data 'od-enkikan004  /name '撮影時刻  /content '午後1時
|-- META  /data 'od-enkikan004  /name '更新頻度  /content '不定期
|-- META  /data 'od-enkikan004  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-enkikan005  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-bunkashisetsu/od-enkikan/od-enkikan005.html"

|-- META  /data 'od-enkikan005  /name 'タイトル  /content '燕喜館と桜3
|-- META  /data 'od-enkikan005  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-enkikan005  /name '住所  /content '新潟市中央区一番堀通町1番地2白山公園内
|-- META  /data 'od-enkikan005  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-enkikan005  /name '公表組織名  /content '新潟市
*** 225

|-- META  /data 'od-enkikan005  /name '実効画像サイズ  /content "幅2496×高さ1664（ピクセル）"
|-- META  /data 'od-enkikan005  /name '撮影日  /content '2014年4月14日
|-- META  /data 'od-enkikan005  /name '撮影時刻  /content '午後4時23分
|-- META  /data 'od-enkikan005  /name '更新頻度  /content '不定期
|-- META  /data 'od-enkikan005  /name "言語・文字コード"  /content "日本語・UTF-8"

|-- META  /data 'od-flower001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-shokutohana/od-flower/od-flower001.html"
|-- META  /data 'od-flower001  /name 'タイトル  /content 'チューリップ畑
|-- META  /data 'od-flower001  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-flower001  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-flower001  /name '実効画像サイズ  /content "幅1715×高さ1139（ピクセル）"

|-- META  /data 'od-flower001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-flower002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-shokutohana/od-flower/od-flower002.html"
|-- META  /data 'od-flower002  /name 'タイトル  /content 'アザレア1
|-- META  /data 'od-flower002  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-flower002  /name "公表者・作成者"  /content "地域・魅力創造部広報課"

|-- META  /data 'od-flower002  /name '実効画像サイズ  /content "幅2832×高さ4256（ピクセル）"
|-- META  /data 'od-flower002  /name '撮影日  /content '2009年
|-- META  /data 'od-flower002  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-flower003  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-shokutohana/od-flower/od-flower003.html"
|-- META  /data 'od-flower003  /name 'タイトル  /content 'クリスマスローズ

|-- META  /data 'od-flower003  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-flower003  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-flower003  /name '実効画像サイズ  /content "幅2067×高さ1375（ピクセル）"
|-- META  /data 'od-flower003  /name '撮影日  /content '2010年
|-- META  /data 'od-flower003  /name "言語・文字コード"  /content "日本語・UTF-8"
*** 250

|-- META  /data 'od-flower004  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-shokutohana/od-flower/od-flower004.html"
|-- META  /data 'od-flower004  /name 'タイトル  /content 'アザレア2
|-- META  /data 'od-flower004  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-flower004  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-flower004  /name '実効画像サイズ  /content "幅2362×高さ1569（ピクセル）"

|-- META  /data 'od-flower004  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-food001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-shokutohana/od-food/od-food001.html"
|-- META  /data 'od-food001  /name 'タイトル  /content '巨峰
|-- META  /data 'od-food001  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-food001  /name "公表者・作成者"  /content "地域・魅力創造部広報課"

|-- META  /data 'od-food001  /name '実効画像サイズ  /content "幅1168×高さ1752（ピクセル）"
|-- META  /data 'od-food001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-food002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-shokutohana/od-food/od-food002.html"
|-- META  /data 'od-food002  /name 'タイトル  /content "ル レクチエ"
|-- META  /data 'od-food002  /name 'ライセンス  /content "表示（CC-BY）"

|-- META  /data 'od-food002  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-food002  /name '実効画像サイズ  /content "幅2336×高さ3504（ピクセル）"
|-- META  /data 'od-food002  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-fukushimagata001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-kata/od-fukushimagata/od-fukushimagata001.html"
|-- META  /data 'od-fukushimagata001  /name 'タイトル  /content '福島潟のオニバス

|-- META  /data 'od-fukushimagata001  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-fukushimagata001  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-fukushimagata001  /name '地域  /content '新潟市北区
|-- META  /data 'od-fukushimagata001  /name '実効画像サイズ  /content "幅2106×高さ1400（ピクセル）"
|-- META  /data 'od-fukushimagata001  /name "言語・文字コード"  /content "日本語・UTF-8"
*** 275

|-- META  /data 'od-fukushimagata002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-kata/od-fukushimagata/od-fukushimagata002.html"
|-- META  /data 'od-fukushimagata002  /name 'タイトル  /content '春の福島潟1
|-- META  /data 'od-fukushimagata002  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-fukushimagata002  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-fukushimagata002  /name '地域  /content '新潟市北区

|-- META  /data 'od-fukushimagata002  /name '実効画像サイズ  /content "幅1600×高さ1200（ピクセル）"
|-- META  /data 'od-fukushimagata002  /name '撮影日  /content '2002年4月6日
|-- META  /data 'od-fukushimagata002  /name '撮影時刻  /content '午前7時58分
|-- META  /data 'od-fukushimagata002  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-fukushimagata003  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-kata/od-fukushimagata/od-fukushimagata003.html"

|-- META  /data 'od-fukushimagata003  /name 'タイトル  /content '夏の福島潟
|-- META  /data 'od-fukushimagata003  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-fukushimagata003  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-fukushimagata003  /name '地域  /content '新潟市北区前新田
|-- META  /data 'od-fukushimagata003  /name '実効画像サイズ  /content "幅5184×高さ3456（ピクセル）"

|-- META  /data 'od-fukushimagata003  /name '撮影日  /content '2014年8月22日
|-- META  /data 'od-fukushimagata003  /name '撮影時刻  /content '午前11時43分
|-- META  /data 'od-fukushimagata003  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-fukushimagata004  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-kata/od-fukushimagata/od-fukushimagata004.html"
|-- META  /data 'od-fukushimagata004  /name 'タイトル  /content '秋の福島潟

|-- META  /data 'od-fukushimagata004  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-fukushimagata004  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-fukushimagata004  /name '地域  /content '新潟市北区
|-- META  /data 'od-fukushimagata004  /name '実効画像サイズ  /content "幅3072×高さ2304（ピクセル）"
|-- META  /data 'od-fukushimagata004  /name '撮影日  /content '2009年10月15日
*** 300

|-- META  /data 'od-fukushimagata004  /name '撮影時刻  /content '午前10時28分
|-- META  /data 'od-fukushimagata004  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-fukushimagata005  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-kata/od-fukushimagata/od-fukushimagata005.html"
|-- META  /data 'od-fukushimagata005  /name 'タイトル  /content '春の福島潟2
|-- META  /data 'od-fukushimagata005  /name 'ライセンス  /content "表示（CC-BY）"

|-- META  /data 'od-fukushimagata005  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-fukushimagata005  /name '地域  /content '新潟市北区
|-- META  /data 'od-fukushimagata005  /name '実効画像サイズ  /content "幅1728×高さ1152（ピクセル）"
|-- META  /data 'od-fukushimagata005  /name '撮影日  /content '2008年4月9日
|-- META  /data 'od-fukushimagata005  /name '撮影時刻  /content '午後0時33分

|-- META  /data 'od-fukushimagata005  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-gis_aed  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kenkofukushi/od-gis_aed.html"
|-- META  /data 'od-gis_aed  /name 'タイトル  /content "AED（自動体外式除細動器）設置施設"
|-- META  /data 'od-gis_aed  /name 'タグ  /content '健康
|-- META  /data 'od-gis_aed  /name 'ファイルサイズ  /content '32KB

|-- META  /data 'od-gis_aed  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_aed  /name '作成者  /content '保健衛生部保健所保健管理課
|-- META  /data 'od-gis_aed  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_aed  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_aed  /name '更新頻度  /content '随時

|-- META  /data 'od-gis_aed  /name '最終更新日  /content '2014年11月21日
|-- META  /data 'od-gis_aed  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_aed  /name '補足
|-- META  /data 'od-gis_asaichi  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kurashibosai/od-gis_asaichi.html"
|-- META  /data 'od-gis_asaichi  /name 'タイトル  /content '朝市
*** 325

|-- META  /data 'od-gis_asaichi  /name 'タグ  /content 'くらし
|-- META  /data 'od-gis_asaichi  /name 'ファイルサイズ  /content '6KB
|-- META  /data 'od-gis_asaichi  /name 'リリース日  /content '2015年3月13日
|-- META  /data 'od-gis_asaichi  /name '作成者  /content '農林水産部食と花の推進課
|-- META  /data 'od-gis_asaichi  /name '使用言語  /content '日本語

|-- META  /data 'od-gis_asaichi  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_asaichi  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_asaichi  /name '最終更新日  /content '2015年2月26日
|-- META  /data 'od-gis_asaichi  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_asaichi  /name '補足

|-- META  /data 'od-gis_bus_hakusan  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kankobunspo/od-gis_dokabengo.html"
|-- META  /data 'od-gis_bus_hakusan  /name 'タイトル  /content '白山公園先回り
|-- META  /data 'od-gis_bus_hakusan  /name 'タグ  /content '観光
|-- META  /data 'od-gis_bus_hakusan  /name 'ファイルサイズ  /content '3キロバイト
|-- META  /data 'od-gis_bus_hakusan  /name 'リリース日  /content '2015年1月15日

|-- META  /data 'od-gis_bus_hakusan  /name '作成者  /content "観光・国際交流部観光政策課"
|-- META  /data 'od-gis_bus_hakusan  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_bus_hakusan  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_bus_hakusan  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_bus_hakusan  /name '最終更新日  /content '2015年4月30日

|-- META  /data 'od-gis_bus_hakusan  /name '組織名  /content '新潟市
|-- META  /data 'od-gis_chisan_inshok  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kurashibosai/od-gis_chisan_inshok.html"
|-- META  /data 'od-gis_chisan_inshok  /name 'タイトル  /content "地産地消推進の店（飲食店）"
|-- META  /data 'od-gis_chisan_inshok  /name 'タグ  /content 'くらし
|-- META  /data 'od-gis_chisan_inshok  /name 'ファイルサイズ  /content '21KB
*** 350

|-- META  /data 'od-gis_chisan_inshok  /name 'リリース日  /content '2015年3月13日
|-- META  /data 'od-gis_chisan_inshok  /name '作成者  /content '農林水産部食と花の推進課
|-- META  /data 'od-gis_chisan_inshok  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_chisan_inshok  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_chisan_inshok  /name '更新頻度  /content '随時

|-- META  /data 'od-gis_chisan_inshok  /name '最終更新日  /content '2015年2月27日
|-- META  /data 'od-gis_chisan_inshok  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_chisan_inshok  /name '補足
|-- META  /data 'od-gis_chisan_kouri  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kurashibosai/od-gis_chisan_kouri.html"
|-- META  /data 'od-gis_chisan_kouri  /name 'タイトル  /content "地産地消推進の店（小売店）"

|-- META  /data 'od-gis_chisan_kouri  /name 'タグ  /content 'くらし
|-- META  /data 'od-gis_chisan_kouri  /name 'ファイルサイズ  /content '9KB
|-- META  /data 'od-gis_chisan_kouri  /name 'リリース日  /content '2015年3月13日
|-- META  /data 'od-gis_chisan_kouri  /name '作成者  /content '農林水産部食と花の推進課
|-- META  /data 'od-gis_chisan_kouri  /name '使用言語  /content '日本語

|-- META  /data 'od-gis_chisan_kouri  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_chisan_kouri  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_chisan_kouri  /name '最終更新日  /content '2015年2月27日
|-- META  /data 'od-gis_chisan_kouri  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_chisan_kouri  /name '補足

|-- META  /data 'od-gis_chugakko  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kosodate/od-gis_chugakko.html"
|-- META  /data 'od-gis_chugakko  /name 'タイトル  /content '中学校
|-- META  /data 'od-gis_chugakko  /name 'タグ  /content "子育て、教育"
|-- META  /data 'od-gis_chugakko  /name 'ファイルサイズ  /content '11KB
|-- META  /data 'od-gis_chugakko  /name 'リリース日  /content '2015年1月30日
*** 375

|-- META  /data 'od-gis_chugakko  /name '作成者  /content "教育委員会事務局教職員課、教育委員会事務局学校支援課"
|-- META  /data 'od-gis_chugakko  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_chugakko  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_chugakko  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_chugakko  /name '最終更新日  /content '2015年1月14日

|-- META  /data 'od-gis_chugakko  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_chugakko  /name '補足
|-- META  /data 'od-gis_community  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kosodate/od-gis_community.html"
|-- META  /data 'od-gis_community  /name 'タイトル  /content '公民館
|-- META  /data 'od-gis_community  /name 'タグ  /content '生涯学習

|-- META  /data 'od-gis_community  /name 'ファイルサイズ  /content '11KB
|-- META  /data 'od-gis_community  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_community  /name '作成者  /content '教育委員会事務局中央公民館
|-- META  /data 'od-gis_community  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_community  /name '公表者  /content '総務部IT推進課

|-- META  /data 'od-gis_community  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_community  /name '最終更新日  /content '2014年11月21日
|-- META  /data 'od-gis_community  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_community  /name '補足
|-- META  /data 'od-gis_communitycent  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kosodate/od-gis_communitycent.html"

|-- META  /data 'od-gis_communitycent  /name 'タイトル  /content 'コミュニティセンター等
|-- META  /data 'od-gis_communitycent  /name 'タグ  /content '生涯学習
|-- META  /data 'od-gis_communitycent  /name 'ファイルサイズ  /content '11KB
|-- META  /data 'od-gis_communitycent  /name 'リリース日  /content '2015年1月30日
|-- META  /data 'od-gis_communitycent  /name '作成者  /content "各区地域課、食育・花育センター、江南区産業振興課、秋葉区産業振興課、南区産業振興課、西区農政商工課、西蒲区産業観光課"
*** 400

|-- META  /data 'od-gis_communitycent  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_communitycent  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_communitycent  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_communitycent  /name '最終更新日  /content '2015年1月17日
|-- META  /data 'od-gis_communitycent  /name '組織名  /content '新潟市役所

|-- META  /data 'od-gis_communitycent  /name '補足
|-- META  /data 'od-gis_dobokujimusho  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kurashibosai/od-gis_dobokujimusho.html"
|-- META  /data 'od-gis_dobokujimusho  /name 'タイトル  /content "土木事務所・駅周辺整備事務所"
|-- META  /data 'od-gis_dobokujimusho  /name 'タグ  /content 'くらし
|-- META  /data 'od-gis_dobokujimusho  /name 'ファイルサイズ  /content '479bytes

|-- META  /data 'od-gis_dobokujimusho  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_dobokujimusho  /name '作成者  /content '総務部総務課
|-- META  /data 'od-gis_dobokujimusho  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_dobokujimusho  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_dobokujimusho  /name '更新頻度  /content '随時

|-- META  /data 'od-gis_dobokujimusho  /name '最終更新日  /content '2011年9月7日
|-- META  /data 'od-gis_dobokujimusho  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_dobokujimusho  /name '補足
|-- META  /data 'od-gis_eiseikankyo  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kenkofukushi/od-gis_eiseikankyo.html"
|-- META  /data 'od-gis_eiseikankyo  /name 'タイトル  /content '衛生環境研究所

|-- META  /data 'od-gis_eiseikankyo  /name 'タグ  /content "健康、福祉"
|-- META  /data 'od-gis_eiseikankyo  /name 'ファイルサイズ  /content '233bytes
|-- META  /data 'od-gis_eiseikankyo  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_eiseikankyo  /name '作成者  /content '保健衛生部衛生環境研究所
|-- META  /data 'od-gis_eiseikankyo  /name '使用言語  /content '日本語
*** 425

|-- META  /data 'od-gis_eiseikankyo  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_eiseikankyo  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_eiseikankyo  /name '最終更新日  /content '2011年9月7日
|-- META  /data 'od-gis_eiseikankyo  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_eiseikankyo  /name '補足

|-- META  /data 'od-gis_farmstand  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kurashibosai/od-gis_farmstand.html"
|-- META  /data 'od-gis_farmstand  /name 'タイトル  /content '農産物直売所
|-- META  /data 'od-gis_farmstand  /name 'タグ  /content 'くらし
|-- META  /data 'od-gis_farmstand  /name 'ファイルサイズ  /content '18KB
|-- META  /data 'od-gis_farmstand  /name 'リリース日  /content '2015年3月13日

|-- META  /data 'od-gis_farmstand  /name '作成者  /content '農林水産部食と花の推進課
|-- META  /data 'od-gis_farmstand  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_farmstand  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_farmstand  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_farmstand  /name '最終更新日  /content '2015年2月27日

|-- META  /data 'od-gis_farmstand  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_farmstand  /name '補足
|-- META  /data 'od-gis_fishingbase  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kurashibosai/od-gis_fishingbase.html"
|-- META  /data 'od-gis_fishingbase  /name 'タイトル  /content '漁業基地
|-- META  /data 'od-gis_fishingbase  /name 'タグ  /content 'くらし

|-- META  /data 'od-gis_fishingbase  /name 'ファイルサイズ  /content '798bytes
|-- META  /data 'od-gis_fishingbase  /name 'リリース日  /content '2015年1月15日
|-- META  /data 'od-gis_fishingbase  /name '作成者  /content '農林水産部食と花の推進課
|-- META  /data 'od-gis_fishingbase  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_fishingbase  /name '公表者  /content '総務部IT推進課
*** 450

|-- META  /data 'od-gis_fishingbase  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_fishingbase  /name '最終更新日  /content '2011年9月7日
|-- META  /data 'od-gis_fishingbase  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_fishingbase  /name '補足
|-- META  /data 'od-gis_forshogaisha  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kenkofukushi/od-gis_forshogaisha.html"

|-- META  /data 'od-gis_forshogaisha  /name 'タイトル  /content '障がい者のための施設
|-- META  /data 'od-gis_forshogaisha  /name 'タグ  /content '福祉
|-- META  /data 'od-gis_forshogaisha  /name 'ファイルサイズ  /content '12KB
|-- META  /data 'od-gis_forshogaisha  /name 'リリース日  /content '2015年1月15日
|-- META  /data 'od-gis_forshogaisha  /name '作成者  /content '福祉部障がい福祉課

|-- META  /data 'od-gis_forshogaisha  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_forshogaisha  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_forshogaisha  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_forshogaisha  /name '最終更新日  /content '2014年11月25日
|-- META  /data 'od-gis_forshogaisha  /name '組織名  /content '新潟市役所

|-- META  /data 'od-gis_forshogaisha  /name '補足
|-- META  /data 'od-gis_gesuido  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_dourosuido/od-gis_gesuido.html"
|-- META  /data 'od-gis_gesuido  /name 'タイトル  /content '下水道施設
|-- META  /data 'od-gis_gesuido  /name 'タグ  /content '上下水道
|-- META  /data 'od-gis_gesuido  /name 'ファイルサイズ  /content '11KB

|-- META  /data 'od-gis_gesuido  /name 'リリース日  /content '2015年1月30日
|-- META  /data 'od-gis_gesuido  /name '作成者  /content '下水道部下水道管理センター
|-- META  /data 'od-gis_gesuido  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_gesuido  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_gesuido  /name '更新頻度  /content '随時
*** 475

|-- META  /data 'od-gis_gesuido  /name '最終更新日  /content '2015年1月17日
|-- META  /data 'od-gis_gesuido  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_gesuido  /name '補足
|-- META  /data 'od-gis_greenandblue  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kankobunspo/od-gis_greenandblue.html"
|-- META  /data 'od-gis_greenandblue  /name 'タイトル  /content "グリーン＆ブルーツーリズム"

|-- META  /data 'od-gis_greenandblue  /name 'タグ  /content '観光
|-- META  /data 'od-gis_greenandblue  /name 'ファイルサイズ  /content '24KB
|-- META  /data 'od-gis_greenandblue  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_greenandblue  /name '作成者  /content "農林水産部食育・花育センター"
|-- META  /data 'od-gis_greenandblue  /name '使用言語  /content '日本語

|-- META  /data 'od-gis_greenandblue  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_greenandblue  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_greenandblue  /name '最終更新日  /content '2014年11月15日
|-- META  /data 'od-gis_greenandblue  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_greenandblue  /name '補足

|-- META  /data 'od-gis_himawari  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kosodate/od-gis_himawari.html"
|-- META  /data 'od-gis_himawari  /name 'タイトル  /content 'ひまわりクラブ
|-- META  /data 'od-gis_himawari  /name 'タグ  /content '子育て
|-- META  /data 'od-gis_himawari  /name 'ファイルサイズ  /content '16KB
|-- META  /data 'od-gis_himawari  /name 'リリース日  /content '2015年2月24日

|-- META  /data 'od-gis_himawari  /name '作成者  /content '福祉部こども未来課
|-- META  /data 'od-gis_himawari  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_himawari  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_himawari  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_himawari  /name '最終更新日  /content '2015年1月27日
*** 500

|-- META  /data 'od-gis_himawari  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_himawari  /name '補足
|-- META  /data 'od-gis_hoikuen  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kenkofukushi/od-gis_hoikuen.html"
|-- META  /data 'od-gis_hoikuen  /name 'タイトル  /content '保育園
|-- META  /data 'od-gis_hoikuen  /name 'タグ  /content '福祉

|-- META  /data 'od-gis_hoikuen  /name 'ファイルサイズ  /content '22KB
|-- META  /data 'od-gis_hoikuen  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_hoikuen  /name '作成者  /content '福祉部保育課
|-- META  /data 'od-gis_hoikuen  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_hoikuen  /name '公表者  /content '総務部IT推進課

|-- META  /data 'od-gis_hoikuen  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_hoikuen  /name '最終更新日  /content '2014年11月18日
|-- META  /data 'od-gis_hoikuen  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_hoikuen  /name '補足
|-- META  /data 'od-gis_hojoten  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_dourosuido/od-gis_hojoten.html"

|-- META  /data 'od-gis_hojoten  /name 'タイトル  /content '補助点
|-- META  /data 'od-gis_hojoten  /name 'タグ  /content '道路
|-- META  /data 'od-gis_hojoten  /name 'ファイルサイズ  /content '445KB
|-- META  /data 'od-gis_hojoten  /name 'リリース日  /content '2015年1月15日
|-- META  /data 'od-gis_hojoten  /name '作成者  /content '土木部土木総務課

|-- META  /data 'od-gis_hojoten  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_hojoten  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_hojoten  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_hojoten  /name '最終更新日  /content '2014年11月27日
|-- META  /data 'od-gis_hojoten  /name '組織名  /content '新潟市役所
*** 525

|-- META  /data 'od-gis_hojoten  /name '補足
|-- META  /data 'od-gis_hokenfukushi  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kenkofukushi/od-gis_hokenfukushi.html"
|-- META  /data 'od-gis_hokenfukushi  /name 'タイトル  /content '地域保健福祉センター等
|-- META  /data 'od-gis_hokenfukushi  /name 'タグ  /content "健康、福祉"
|-- META  /data 'od-gis_hokenfukushi  /name 'ファイルサイズ  /content '5KB

|-- META  /data 'od-gis_hokenfukushi  /name 'リリース日  /content '2015年1月30日
|-- META  /data 'od-gis_hokenfukushi  /name '作成者  /content "各区健康福祉課、福祉部福祉総務課、南区地域課"
|-- META  /data 'od-gis_hokenfukushi  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_hokenfukushi  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_hokenfukushi  /name '更新頻度  /content '随時

|-- META  /data 'od-gis_hokenfukushi  /name '最終更新日  /content '2015年1月17日
|-- META  /data 'od-gis_hokenfukushi  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_hokenfukushi  /name '補足
|-- META  /data 'od-gis_hokenjo  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kenkofukushi/od-gis_hokenjo.html"
|-- META  /data 'od-gis_hokenjo  /name 'タイトル  /content '保健所

|-- META  /data 'od-gis_hokenjo  /name 'タグ  /content "健康、福祉"
|-- META  /data 'od-gis_hokenjo  /name 'ファイルサイズ  /content '702bytes
|-- META  /data 'od-gis_hokenjo  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_hokenjo  /name '作成者  /content "保健衛生部保健所保健管理課、保健衛生部保健所食の安全推進課"
|-- META  /data 'od-gis_hokenjo  /name '使用言語  /content '日本語

|-- META  /data 'od-gis_hokenjo  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_hokenjo  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_hokenjo  /name '最終更新日  /content '2014年11月12日
|-- META  /data 'od-gis_hokenjo  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_hokenjo  /name '補足
*** 550

|-- META  /data 'od-gis_inuyashago  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kankobunspo/od-gis_inuyashago.html"
|-- META  /data 'od-gis_inuyashago  /name 'タイトル  /content "朱鷺メッセ先回り（犬夜叉号）"
|-- META  /data 'od-gis_inuyashago  /name 'タグ  /content '観光
|-- META  /data 'od-gis_inuyashago  /name 'ファイルサイズ  /content '3KB
|-- META  /data 'od-gis_inuyashago  /name 'リリース日  /content '2015年1月15日

|-- META  /data 'od-gis_inuyashago  /name '作成者  /content "観光・国際交流部観光政策課"
|-- META  /data 'od-gis_inuyashago  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_inuyashago  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_inuyashago  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_inuyashago  /name '最終更新日  /content '2014年12月22日

|-- META  /data 'od-gis_inuyashago  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_inuyashago  /name '補足
|-- META  /data 'od-gis_iseki  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kankobunspo/od-gis_iseki.html"
|-- META  /data 'od-gis_iseki  /name 'タイトル  /content '遺跡
|-- META  /data 'od-gis_iseki  /name 'タグ  /content '文化

|-- META  /data 'od-gis_iseki  /name 'ファイルサイズ  /content '281KB
|-- META  /data 'od-gis_iseki  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_iseki  /name '作成者  /content '文化スポーツ部歴史文化課
|-- META  /data 'od-gis_iseki  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_iseki  /name '公表者  /content '総務部IT推進課

|-- META  /data 'od-gis_iseki  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_iseki  /name '最終更新日  /content '2014年11月14日
|-- META  /data 'od-gis_iseki  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_iseki  /name '補足
|-- META  /data 'od-gis_jidocenter  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kosodate/od-gis_jidocenter.html"
*** 575

|-- META  /data 'od-gis_jidocenter  /name 'タイトル  /content '児童センター等
|-- META  /data 'od-gis_jidocenter  /name 'タグ  /content '子育て
|-- META  /data 'od-gis_jidocenter  /name 'ファイルサイズ  /content '4KB
|-- META  /data 'od-gis_jidocenter  /name 'リリース日  /content '2015年1月15日
|-- META  /data 'od-gis_jidocenter  /name '作成者  /content '福祉部こども未来課

|-- META  /data 'od-gis_jidocenter  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_jidocenter  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_jidocenter  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_jidocenter  /name '最終更新日  /content '2014年12月30日
|-- META  /data 'od-gis_jidocenter  /name '組織名  /content '新潟市役所

|-- META  /data 'od-gis_jidocenter  /name '補足
|-- META  /data 'od-gis_kendo_hashi  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_dourosuido/od-gis_kendo_hashi.html"
|-- META  /data 'od-gis_kendo_hashi  /name 'タイトル  /content '県道上の橋梁
|-- META  /data 'od-gis_kendo_hashi  /name 'タグ  /content '道路
|-- META  /data 'od-gis_kendo_hashi  /name 'ファイルサイズ  /content '54KB

|-- META  /data 'od-gis_kendo_hashi  /name 'リリース日  /content '2015年2月24日
|-- META  /data 'od-gis_kendo_hashi  /name '作成者  /content '土木部土木総務課
|-- META  /data 'od-gis_kendo_hashi  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_kendo_hashi  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_kendo_hashi  /name '更新頻度  /content '随時

|-- META  /data 'od-gis_kendo_hashi  /name '最終更新日  /content '2015年2月14日
|-- META  /data 'od-gis_kendo_hashi  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_kendo_hashi  /name '補足
|-- META  /data 'od-gis_kenko_ben  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kenkofukushi/od-gis_kenko_ben.html"
|-- META  /data 'od-gis_kenko_ben  /name 'タイトル  /content "健康づくり支援店（弁当類またはそうざい類の販売）"
*** 600

|-- META  /data 'od-gis_kenko_ben  /name 'タグ  /content '健康
|-- META  /data 'od-gis_kenko_ben  /name 'ファイルサイズ  /content '30KB
|-- META  /data 'od-gis_kenko_ben  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_kenko_ben  /name '作成者  /content '保健衛生部保健所健康増進課
|-- META  /data 'od-gis_kenko_ben  /name '使用言語  /content '日本語

|-- META  /data 'od-gis_kenko_ben  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_kenko_ben  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_kenko_ben  /name '最終更新日  /content '2014年11月23日
|-- META  /data 'od-gis_kenko_ben  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_kenko_ben  /name '補足

|-- META  /data 'od-gis_kenko_in  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kenkofukushi/od-gis_kenko_in.html"
|-- META  /data 'od-gis_kenko_in  /name 'タイトル  /content "健康づくり支援店（飲食店またはそうざい製造業）"
|-- META  /data 'od-gis_kenko_in  /name 'タグ  /content '健康
|-- META  /data 'od-gis_kenko_in  /name 'ファイルサイズ  /content '37KB
|-- META  /data 'od-gis_kenko_in  /name 'リリース日  /content '2014年12月4日

|-- META  /data 'od-gis_kenko_in  /name '作成者  /content '保健衛生部保健所健康増進課
|-- META  /data 'od-gis_kenko_in  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_kenko_in  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_kenko_in  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_kenko_in  /name '最終更新日  /content '2014年11月23日

|-- META  /data 'od-gis_kenko_in  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_kenko_in  /name '補足
|-- META  /data 'od-gis_kenko_kyu  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kenkofukushi/od-gis_kenko_kyu.html"
|-- META  /data 'od-gis_kenko_kyu  /name 'タイトル  /content "健康づくり支援店（特定給食施設または特定給食施設以外の施設）"
|-- META  /data 'od-gis_kenko_kyu  /name 'タグ  /content '健康
*** 625

|-- META  /data 'od-gis_kenko_kyu  /name 'ファイルサイズ  /content '3KB
|-- META  /data 'od-gis_kenko_kyu  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_kenko_kyu  /name '作成者  /content '保健衛生部保健所健康増進課
|-- META  /data 'od-gis_kenko_kyu  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_kenko_kyu  /name '公表者  /content '総務部IT推進課

|-- META  /data 'od-gis_kenko_kyu  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_kenko_kyu  /name '最終更新日  /content '2013年10月22日
|-- META  /data 'od-gis_kenko_kyu  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_kenko_kyu  /name '補足
|-- META  /data 'od-gis_kokudo_hashi  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_dourosuido/od-gis_kokudo_hashi.html"

|-- META  /data 'od-gis_kokudo_hashi  /name 'タイトル  /content '国道上の橋梁
|-- META  /data 'od-gis_kokudo_hashi  /name 'タグ  /content '道路
|-- META  /data 'od-gis_kokudo_hashi  /name 'ファイルサイズ  /content '18KB
|-- META  /data 'od-gis_kokudo_hashi  /name 'リリース日  /content '2015年2月24日
|-- META  /data 'od-gis_kokudo_hashi  /name '作成者  /content '土木部土木総務課

|-- META  /data 'od-gis_kokudo_hashi  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_kokudo_hashi  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_kokudo_hashi  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_kokudo_hashi  /name '最終更新日  /content '2015年2月14日
|-- META  /data 'od-gis_kokudo_hashi  /name '組織名  /content '新潟市役所

|-- META  /data 'od-gis_kokudo_hashi  /name '補足
|-- META  /data 'od-gis_library  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kosodate/od-gis_library.html"
|-- META  /data 'od-gis_library  /name 'タイトル  /content '図書館
|-- META  /data 'od-gis_library  /name 'タグ  /content '生涯学習
|-- META  /data 'od-gis_library  /name 'ファイルサイズ  /content '6KB
*** 650

|-- META  /data 'od-gis_library  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_library  /name '作成者  /content '教育委員会事務局中央図書館
|-- META  /data 'od-gis_library  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_library  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_library  /name '更新頻度  /content '随時

|-- META  /data 'od-gis_library  /name '最終更新日  /content '2014年11月16日
|-- META  /data 'od-gis_library  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_library  /name '補足
|-- META  /data 'od-gis_okugaihinan  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kurashibosai/od-gis_okugaihinan.html"
|-- META  /data 'od-gis_okugaihinan  /name 'タイトル  /content '屋外避難場所

|-- META  /data 'od-gis_okugaihinan  /name 'タグ  /content '防災
|-- META  /data 'od-gis_okugaihinan  /name 'ファイルサイズ  /content '58KB
|-- META  /data 'od-gis_okugaihinan  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_okugaihinan  /name '作成者  /content '危機管理防災局防災課
|-- META  /data 'od-gis_okugaihinan  /name '使用言語  /content '日本語

|-- META  /data 'od-gis_okugaihinan  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_okugaihinan  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_okugaihinan  /name '最終更新日  /content '2014年11月11日
|-- META  /data 'od-gis_okugaihinan  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_okugaihinan  /name '補足

|-- META  /data 'od-gis_okunaihinanjo  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kurashibosai/od-gis_okunaihinanjo.html"
|-- META  /data 'od-gis_okunaihinanjo  /name 'タイトル  /content '屋内避難所
|-- META  /data 'od-gis_okunaihinanjo  /name 'タグ  /content '防災
|-- META  /data 'od-gis_okunaihinanjo  /name 'ファイルサイズ  /content '172KB
|-- META  /data 'od-gis_okunaihinanjo  /name 'リリース日  /content '2015年1月15日
*** 675

|-- META  /data 'od-gis_okunaihinanjo  /name '作成者  /content '危機管理防災局防災課
|-- META  /data 'od-gis_okunaihinanjo  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_okunaihinanjo  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_okunaihinanjo  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_okunaihinanjo  /name '最終更新日  /content '2015年1月5日

|-- META  /data 'od-gis_okunaihinanjo  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_okunaihinanjo  /name '補足
|-- META  /data 'od-gis_onseninst  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kankobunspo/od-gis_onseninst.html"
|-- META  /data 'od-gis_onseninst  /name 'タイトル  /content '温泉利用を許可した施設
|-- META  /data 'od-gis_onseninst  /name 'タグ  /content "観光、健康"

|-- META  /data 'od-gis_onseninst  /name 'ファイルサイズ  /content '4KB
|-- META  /data 'od-gis_onseninst  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_onseninst  /name '作成者  /content '保健衛生部保健所環境衛生課
|-- META  /data 'od-gis_onseninst  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_onseninst  /name '公表者  /content '総務部IT推進課

|-- META  /data 'od-gis_onseninst  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_onseninst  /name '最終更新日  /content '2014年11月13日
|-- META  /data 'od-gis_onseninst  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_onseninst  /name '補足
|-- META  /data 'od-gis_park  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kurashibosai/od-gis_park.html"

|-- META  /data 'od-gis_park  /name 'タイトル  /content "公園・緑地"
|-- META  /data 'od-gis_park  /name 'タグ  /content 'くらし
|-- META  /data 'od-gis_park  /name 'ファイルサイズ  /content '142KB
|-- META  /data 'od-gis_park  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_park  /name '作成者  /content '土木部公園水辺課
*** 700

|-- META  /data 'od-gis_park  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_park  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_park  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_park  /name '最終更新日  /content '2014年11月17日
|-- META  /data 'od-gis_park  /name '組織名  /content '新潟市役所

|-- META  /data 'od-gis_park  /name '補足
|-- META  /data 'od-gis_pkbicycles  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kankobunspo/od-gis_pkbicycles.html"
|-- META  /data 'od-gis_pkbicycles  /name 'タイトル  /content '駐輪場
|-- META  /data 'od-gis_pkbicycles  /name 'タグ  /content '観光
|-- META  /data 'od-gis_pkbicycles  /name 'ファイルサイズ  /content '10KB

|-- META  /data 'od-gis_pkbicycles  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_pkbicycles  /name '作成者  /content '土木部土木総務課
|-- META  /data 'od-gis_pkbicycles  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_pkbicycles  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_pkbicycles  /name '更新頻度  /content '随時

|-- META  /data 'od-gis_pkbicycles  /name '最終更新日  /content '2014年11月14日
|-- META  /data 'od-gis_pkbicycles  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_pkbicycles  /name '補足
|-- META  /data 'od-gis_rentcycle  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kankobunspo/od-gis_rentcycle.html"
|-- META  /data 'od-gis_rentcycle  /name 'タイトル  /content "レンタサイクル（新潟地区）"

|-- META  /data 'od-gis_rentcycle  /name 'タグ  /content '観光
|-- META  /data 'od-gis_rentcycle  /name 'ファイルサイズ  /content '6KB
|-- META  /data 'od-gis_rentcycle  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_rentcycle  /name '作成者  /content '中央区建設課
|-- META  /data 'od-gis_rentcycle  /name '使用言語  /content '日本語
*** 725

|-- META  /data 'od-gis_rentcycle  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_rentcycle  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_rentcycle  /name '最終更新日  /content '2014年11月15日
|-- META  /data 'od-gis_rentcycle  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_rentcycle  /name '補足

|-- META  /data 'od-gis_sankakuten  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_dourosuido/od-gis_sankakuten.html"
|-- META  /data 'od-gis_sankakuten  /name 'タイトル  /content '街区三角点
|-- META  /data 'od-gis_sankakuten  /name 'タグ  /content '道路
|-- META  /data 'od-gis_sankakuten  /name 'ファイルサイズ  /content '32KB
|-- META  /data 'od-gis_sankakuten  /name 'リリース日  /content '2015年1月15日

|-- META  /data 'od-gis_sankakuten  /name '作成者  /content '土木部土木総務課
|-- META  /data 'od-gis_sankakuten  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_sankakuten  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_sankakuten  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_sankakuten  /name '最終更新日  /content '2014年11月27日

|-- META  /data 'od-gis_sankakuten  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_sankakuten  /name '補足
|-- META  /data 'od-gis_sankakuten_np  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_dourosuido/od-gis_sankakuten_np.html"
|-- META  /data 'od-gis_sankakuten_np  /name 'タイトル  /content "街区三角点（節点）"
|-- META  /data 'od-gis_sankakuten_np  /name 'タグ  /content '道路

|-- META  /data 'od-gis_sankakuten_np  /name 'ファイルサイズ  /content '14KB
|-- META  /data 'od-gis_sankakuten_np  /name 'リリース日  /content '2015年1月15日
|-- META  /data 'od-gis_sankakuten_np  /name '作成者  /content '土木部土木総務課
|-- META  /data 'od-gis_sankakuten_np  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_sankakuten_np  /name '公表者  /content '総務部IT推進課
*** 750

|-- META  /data 'od-gis_sankakuten_np  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_sankakuten_np  /name '最終更新日  /content '2014年11月27日
|-- META  /data 'od-gis_sankakuten_np  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_sankakuten_np  /name '補足
|-- META  /data 'od-gis_shido_hashi  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_dourosuido/od-gis_shido_hashi.html"

|-- META  /data 'od-gis_shido_hashi  /name 'タイトル  /content '市道上の橋梁
|-- META  /data 'od-gis_shido_hashi  /name 'タグ  /content '道路
|-- META  /data 'od-gis_shido_hashi  /name 'ファイルサイズ  /content '492KB
|-- META  /data 'od-gis_shido_hashi  /name 'リリース日  /content '2015年2月24日
|-- META  /data 'od-gis_shido_hashi  /name '作成者  /content '土木部土木総務課

|-- META  /data 'od-gis_shido_hashi  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_shido_hashi  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_shido_hashi  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_shido_hashi  /name '最終更新日  /content '2015年2月14日
|-- META  /data 'od-gis_shido_hashi  /name '組織名  /content '新潟市役所

|-- META  /data 'od-gis_shido_hashi  /name '補足
|-- META  /data 'od-gis_shieijutaku  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kurashibosai/od-gis_shieijutaku.html"
|-- META  /data 'od-gis_shieijutaku  /name 'タイトル  /content '市営住宅など
|-- META  /data 'od-gis_shieijutaku  /name 'タグ  /content 'くらし
|-- META  /data 'od-gis_shieijutaku  /name 'ファイルサイズ  /content '25KB

|-- META  /data 'od-gis_shieijutaku  /name 'リリース日  /content '2015年1月15日
|-- META  /data 'od-gis_shieijutaku  /name '作成者  /content '建築部住環境政策課
|-- META  /data 'od-gis_shieijutaku  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_shieijutaku  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_shieijutaku  /name '更新頻度  /content '随時
*** 775

|-- META  /data 'od-gis_shieijutaku  /name '最終更新日  /content '2014年12月30日
|-- META  /data 'od-gis_shieijutaku  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_shieijutaku  /name '補足
|-- META  /data 'od-gis_shiminkaikan  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kosodate/od-gis_shiminkaikan.html"
|-- META  /data 'od-gis_shiminkaikan  /name 'タイトル  /content '市民会館等

|-- META  /data 'od-gis_shiminkaikan  /name 'タグ  /content '生涯学習
|-- META  /data 'od-gis_shiminkaikan  /name 'ファイルサイズ  /content '5KB
|-- META  /data 'od-gis_shiminkaikan  /name 'リリース日  /content '2015年1月30日
|-- META  /data 'od-gis_shiminkaikan  /name '作成者  /content "各区地域課、市民生活部男女共同参画課、文化スポーツ部文化政策課、江南区産業振興課、南区産業振興課、教育委員会事務局生涯学習課、教育委員会事務局生涯学習センター、教育委員会事務局白根地区公民館、教育委員会事務局西川地区公民館、教育委員会事務局西川図書館"
|-- META  /data 'od-gis_shiminkaikan  /name '使用言語  /content '日本語

|-- META  /data 'od-gis_shiminkaikan  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_shiminkaikan  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_shiminkaikan  /name '最終更新日  /content '2015年1月30日
|-- META  /data 'od-gis_shiminkaikan  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_shiminkaikan  /name '補足

|-- META  /data 'od-gis_shiminnoen  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kankobunspo/od-gis_shiminnoen.html"
|-- META  /data 'od-gis_shiminnoen  /name 'タイトル  /content '市民農園
|-- META  /data 'od-gis_shiminnoen  /name 'タグ  /content '観光
|-- META  /data 'od-gis_shiminnoen  /name 'ファイルサイズ  /content '3KB
|-- META  /data 'od-gis_shiminnoen  /name 'リリース日  /content '2014年12月4日

|-- META  /data 'od-gis_shiminnoen  /name '作成者  /content "農林水産部食育・花育センター"
|-- META  /data 'od-gis_shiminnoen  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_shiminnoen  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_shiminnoen  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_shiminnoen  /name '最終更新日  /content '2014年11月15日
*** 800

|-- META  /data 'od-gis_shiminnoen  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_shiminnoen  /name '補足
|-- META  /data 'od-gis_shiyakusho  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kurashibosai/od-gis_shiyakusho.html"
|-- META  /data 'od-gis_shiyakusho  /name 'タイトル  /content "市役所・区役所・出張所等"
|-- META  /data 'od-gis_shiyakusho  /name 'タグ  /content 'くらし

|-- META  /data 'od-gis_shiyakusho  /name 'ファイルサイズ  /content '4KB
|-- META  /data 'od-gis_shiyakusho  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_shiyakusho  /name '作成者  /content '総務部総務課
|-- META  /data 'od-gis_shiyakusho  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_shiyakusho  /name '公表者  /content '総務部IT推進課

|-- META  /data 'od-gis_shiyakusho  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_shiyakusho  /name '最終更新日  /content '2014年3月19日
|-- META  /data 'od-gis_shiyakusho  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_shiyakusho  /name '補足
|-- META  /data 'od-gis_shobo  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kurashibosai/od-gis_shobo.html"

|-- META  /data 'od-gis_shobo  /name 'タイトル  /content '消防施設
|-- META  /data 'od-gis_shobo  /name 'タグ  /content "くらし、防災"
|-- META  /data 'od-gis_shobo  /name 'ファイルサイズ  /content '5KB
|-- META  /data 'od-gis_shobo  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_shobo  /name '作成者  /content '消防局総務課

|-- META  /data 'od-gis_shobo  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_shobo  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_shobo  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_shobo  /name '最終更新日  /content '2014年10月3日
|-- META  /data 'od-gis_shobo  /name '組織名  /content '新潟市役所
*** 825

|-- META  /data 'od-gis_shobo  /name '補足
|-- META  /data 'od-gis_shogakko  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kosodate/od-gis_shogakko.html"
|-- META  /data 'od-gis_shogakko  /name 'タイトル  /content '小学校
|-- META  /data 'od-gis_shogakko  /name 'タグ  /content "子育て、教育"
|-- META  /data 'od-gis_shogakko  /name 'ファイルサイズ  /content '20KB

|-- META  /data 'od-gis_shogakko  /name 'リリース日  /content '2015年1月30日
|-- META  /data 'od-gis_shogakko  /name '作成者  /content '教育委員会事務局教職員課
|-- META  /data 'od-gis_shogakko  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_shogakko  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_shogakko  /name '更新頻度  /content '随時

|-- META  /data 'od-gis_shogakko  /name '最終更新日  /content '2015年1月9日
|-- META  /data 'od-gis_shogakko  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_shogakko  /name '補足
|-- META  /data 'od-gis_shokuniku  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kenkofukushi/od-gis_shokuniku.html"
|-- META  /data 'od-gis_shokuniku  /name 'タイトル  /content '食肉衛生検査所

|-- META  /data 'od-gis_shokuniku  /name 'タグ  /content "健康、福祉"
|-- META  /data 'od-gis_shokuniku  /name 'ファイルサイズ  /content '312bytes
|-- META  /data 'od-gis_shokuniku  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_shokuniku  /name '作成者  /content '保健衛生部食肉衛生検査所
|-- META  /data 'od-gis_shokuniku  /name '使用言語  /content '日本語

|-- META  /data 'od-gis_shokuniku  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_shokuniku  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_shokuniku  /name '最終更新日  /content '2014年11月23日
|-- META  /data 'od-gis_shokuniku  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_shokuniku  /name '補足
*** 850

|-- META  /data 'od-gis_sports  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kankobunspo/od-gis_sports.html"
|-- META  /data 'od-gis_sports  /name 'タイトル  /content 'スポーツ施設
|-- META  /data 'od-gis_sports  /name 'タグ  /content 'スポーツ
|-- META  /data 'od-gis_sports  /name 'ファイルサイズ  /content '34KB
|-- META  /data 'od-gis_sports  /name 'リリース日  /content '2015年2月24日

|-- META  /data 'od-gis_sports  /name '作成者  /content "文化スポーツ部スポーツ振興課、環境部廃棄物政策課、東区建設課、中央区建設課、江南区建設課、南区産業振興課"
|-- META  /data 'od-gis_sports  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_sports  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_sports  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_sports  /name '最終更新日  /content '2015年2月18日

|-- META  /data 'od-gis_sports  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_sports  /name '補足
|-- META  /data 'od-gis_takakuten  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_dourosuido/od-gis_takakuten.html"
|-- META  /data 'od-gis_takakuten  /name 'タイトル  /content '街区多角点
|-- META  /data 'od-gis_takakuten  /name 'タグ  /content '道路

|-- META  /data 'od-gis_takakuten  /name 'ファイルサイズ  /content '159KB
|-- META  /data 'od-gis_takakuten  /name 'リリース日  /content '2015年1月15日
|-- META  /data 'od-gis_takakuten  /name '作成者  /content '土木部土木総務課
|-- META  /data 'od-gis_takakuten  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_takakuten  /name '公表者  /content '総務部IT推進課

|-- META  /data 'od-gis_takakuten  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_takakuten  /name '最終更新日  /content '2014年11月27日
|-- META  /data 'od-gis_takakuten  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_takakuten  /name '補足
|-- META  /data 'od-gis_takakuten_np  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_dourosuido/od-gis_takakuten_np.html"
*** 875

|-- META  /data 'od-gis_takakuten_np  /name 'タイトル  /content "街区多角点（節点）"
|-- META  /data 'od-gis_takakuten_np  /name 'タグ  /content '道路
|-- META  /data 'od-gis_takakuten_np  /name 'ファイルサイズ  /content '165KB
|-- META  /data 'od-gis_takakuten_np  /name 'リリース日  /content '2015年1月15日
|-- META  /data 'od-gis_takakuten_np  /name '作成者  /content '土木部土木総務課

|-- META  /data 'od-gis_takakuten_np  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_takakuten_np  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_takakuten_np  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_takakuten_np  /name '最終更新日  /content '2014年11月27日
|-- META  /data 'od-gis_takakuten_np  /name '組織名  /content '新潟市役所

|-- META  /data 'od-gis_takakuten_np  /name '補足
|-- META  /data 'od-gis_waterworksins  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_dourosuido/od-gis_waterworksins.html"
|-- META  /data 'od-gis_waterworksins  /name 'タイトル  /content '上水道施設
|-- META  /data 'od-gis_waterworksins  /name 'タグ  /content '上下水道
|-- META  /data 'od-gis_waterworksins  /name 'ファイルサイズ  /content '4KB

|-- META  /data 'od-gis_waterworksins  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_waterworksins  /name '作成者  /content '水道局総務部総務課
|-- META  /data 'od-gis_waterworksins  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_waterworksins  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_waterworksins  /name '更新頻度  /content '随時

|-- META  /data 'od-gis_waterworksins  /name '最終更新日  /content '2014年11月14日
|-- META  /data 'od-gis_waterworksins  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_waterworksins  /name '補足
|-- META  /data 'od-gis_wifi  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kankobunspo/od-gis_wi-fi.html"
|-- META  /data 'od-gis_wifi  /name 'タイトル  /content '公衆Wi-Fi設置公共施設
*** 900

|-- META  /data 'od-gis_wifi  /name 'タグ  /content "くらし、観光、スポーツ"
|-- META  /data 'od-gis_wifi  /name 'ファイルサイズ  /content '7キロバイト
|-- META  /data 'od-gis_wifi  /name 'リリース日  /content '2015年4月30日
|-- META  /data 'od-gis_wifi  /name '作成者  /content '総務部IT推進課
|-- META  /data 'od-gis_wifi  /name '使用言語  /content "日本語・UTF-8"

|-- META  /data 'od-gis_wifi  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_wifi  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_wifi  /name '最終更新日  /content '2015年4月30日
|-- META  /data 'od-gis_wifi  /name '組織名  /content '新潟市
|-- META  /data 'od-gis_wtf  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kurashibosai/od-gis_wtf.html"

|-- META  /data 'od-gis_wtf  /name 'タイトル  /content '廃棄物処理施設
|-- META  /data 'od-gis_wtf  /name 'タグ  /content 'くらし
|-- META  /data 'od-gis_wtf  /name 'ファイルサイズ  /content '4KB
|-- META  /data 'od-gis_wtf  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-gis_wtf  /name '作成者  /content "環境部廃棄物対策課,環境部廃棄物施設課"

|-- META  /data 'od-gis_wtf  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_wtf  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_wtf  /name '更新頻度  /content '随時
|-- META  /data 'od-gis_wtf  /name '最終更新日  /content '2014年11月23日
|-- META  /data 'od-gis_wtf  /name '組織名  /content '新潟市役所

|-- META  /data 'od-gis_wtf  /name '補足
|-- META  /data 'od-gis_yochien  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gis/od-gis_kosodate/od-gis_yochien.html"
|-- META  /data 'od-gis_yochien  /name 'タイトル  /content '幼稚園
|-- META  /data 'od-gis_yochien  /name 'タグ  /content "子育て、教育"
|-- META  /data 'od-gis_yochien  /name 'ファイルサイズ  /content '8KB
*** 925

|-- META  /data 'od-gis_yochien  /name 'リリース日  /content '2015年1月30日
|-- META  /data 'od-gis_yochien  /name '作成者  /content "教育委員会事務局教職員課、福祉部こども未来課"
|-- META  /data 'od-gis_yochien  /name '使用言語  /content '日本語
|-- META  /data 'od-gis_yochien  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-gis_yochien  /name '更新頻度  /content '随時

|-- META  /data 'od-gis_yochien  /name '最終更新日  /content '2015年1月14日
|-- META  /data 'od-gis_yochien  /name '組織名  /content '新潟市役所
|-- META  /data 'od-gis_yochien  /name '補足
|-- META  /data 'od-h17kokuchonenrei  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-toukei/od-kokucho/od-h17kokuchou/od-h17kokuchonenrei.html"
|-- META  /data 'od-h17kokuchonenrei  /name 'タイトル  /content "【平成17年国勢調査】区別男女別年齢別人口"

|-- META  /data 'od-h17kokuchonenrei  /name 'タグ  /content '国勢調査
|-- META  /data 'od-h17kokuchonenrei  /name 'ファイルサイズ  /content '12キロバイト
|-- META  /data 'od-h17kokuchonenrei  /name 'ライセンス  /content "CC-BY（表示）"
|-- META  /data 'od-h17kokuchonenrei  /name 'リリース日  /content '2015年7月2日
|-- META  /data 'od-h17kokuchonenrei  /name '作成者  /content '総務部総務課

|-- META  /data 'od-h17kokuchonenrei  /name '使用言語  /content "日本語・UTF-8"
|-- META  /data 'od-h17kokuchonenrei  /name '公表組織名  /content '新潟市
|-- META  /data 'od-h17kokuchonenrei  /name '最終更新日  /content '2015年7月2日
|-- META  /data 'od-h17kokuchonenrei  /name '補足1  /content "本ファイルは、平成17年10月1日実施の国勢調査結果に基づいた人口です。"
|-- META  /data 'od-h17kokuchonenrei  /name '補足2  /content "調査日現在では巻町との合併（平成17年10月10日）は行われていませんでしたが、現在の市域（合併後）に組み替えて掲載しています。"

|-- META  /data 'od-h17kokuchonenrei  /name '補足3  /content "調査日現在では政令指定都市への移行、行政区の設置は行われていませんでしたが、行政区ごとの数値を掲載しています。"
|-- META  /data 'od-h17kokuchonenrei  /name '補足4  /content "本ファイルには、世帯数の掲載はありません。"
|-- META  /data 'od-h17kokuchonenrei  /name '補足5  /content "本ファイルの「全年齢」には、「年齢不詳」を含みます。"
|-- META  /data 'od-h17kokuchonenrei  /name '調査日  /content "2005年（平成17年）10月1日"
|-- META  /data 'od-h17kokuchosetai  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-toukei/od-kokucho/od-h17kokuchou/od-h17kokuchosetai.html"
*** 950

|-- META  /data 'od-h17kokuchosetai  /name 'タイトル  /content "【平成17年国勢調査】区・世帯の種類（2区分）・世帯人員（10区分）別世帯数及び世帯人員"
|-- META  /data 'od-h17kokuchosetai  /name 'タグ  /content '国勢調査
|-- META  /data 'od-h17kokuchosetai  /name 'ファイルサイズ  /content '1キロバイト
|-- META  /data 'od-h17kokuchosetai  /name 'ライセンス  /content "CC-BY（表示）"
|-- META  /data 'od-h17kokuchosetai  /name 'リリース日  /content '2015年7月2日

|-- META  /data 'od-h17kokuchosetai  /name '作成者  /content '総務部総務課
|-- META  /data 'od-h17kokuchosetai  /name '使用言語  /content "日本語・UTF-8"
|-- META  /data 'od-h17kokuchosetai  /name '公表組織名  /content '新潟市
|-- META  /data 'od-h17kokuchosetai  /name '最終更新日  /content '2015年7月2日
|-- META  /data 'od-h17kokuchosetai  /name '補足1  /content "本ファイルは、平成17年10月1日実施の国勢調査結果に基づいた世帯数及び世帯人員です。"

|-- META  /data 'od-h17kokuchosetai  /name '補足2  /content "調査日現在では巻町との合併（平成17年10月10日）は行われていませんでしたが、現在の市域（合併後）に組み替えて掲載しています。"
|-- META  /data 'od-h17kokuchosetai  /name '補足3  /content "調査日現在では政令指定都市への移行、行政区の設置は行われていませんでしたが、行政区ごとの数値を掲載しています。"
|-- META  /data 'od-h17kokuchosetai  /name '補足4  /content "本ファイルには、年齢別数値の掲載はありません。"
|-- META  /data 'od-h17kokuchosetai  /name '補足5  /content "本ファイルの「総世帯数」「総世帯人員」には、「不詳」を含みます。"
|-- META  /data 'od-h17kokuchosetai  /name '調査日  /content "2005年（平成17年）10月1日"

|-- META  /data 'od-h17kokuchosyugyo  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-toukei/od-kokucho/od-h17kokuchou/od-h17kokuchosyugyo.html"
|-- META  /data 'od-h17kokuchosyugyo  /name 'タイトル  /content "【平成17年国勢調査】区・産業（大分類）・男女別15歳以上就業者数"
|-- META  /data 'od-h17kokuchosyugyo  /name 'タグ  /content '国勢調査
|-- META  /data 'od-h17kokuchosyugyo  /name 'ファイルサイズ  /content '3キロバイト
|-- META  /data 'od-h17kokuchosyugyo  /name 'ライセンス  /content "CC-BY（表示）"

|-- META  /data 'od-h17kokuchosyugyo  /name 'リリース日  /content '2015年7月2日
|-- META  /data 'od-h17kokuchosyugyo  /name '作成者  /content '総務部総務課
|-- META  /data 'od-h17kokuchosyugyo  /name '使用言語  /content "日本語・UTF-8"
|-- META  /data 'od-h17kokuchosyugyo  /name '公表組織名  /content '新潟市
|-- META  /data 'od-h17kokuchosyugyo  /name '最終更新日  /content '2015年7月2日
*** 975

|-- META  /data 'od-h17kokuchosyugyo  /name '補足1  /content "本ファイルは、平成17年10月1日実施の国勢調査結果に基づいた就業者数です。"
|-- META  /data 'od-h17kokuchosyugyo  /name '補足2  /content "調査日現在では巻町との合併（平成17年10月10日）は行われていませんでしたが、現在の市域（合併後）に組み替えて掲載しています。"
|-- META  /data 'od-h17kokuchosyugyo  /name '補足3  /content "調査日現在では政令指定都市への移行、行政区の設置は行われていませんでしたが、行政区ごとの数値を掲載しています。"
|-- META  /data 'od-h17kokuchosyugyo  /name '補足4  /content "本ファイルには、年齢別数値の掲載はありません。"
|-- META  /data 'od-h17kokuchosyugyo  /name '補足5  /content "本ファイルの「総数」には、「分類不能の産業」を含みます。"

|-- META  /data 'od-h17kokuchosyugyo  /name '調査日  /content "2005年（平成17年）10月1日"
|-- META  /data 'od-h22kokuchonenrei  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-toukei/od-kokucho/od-h22kokuchou/od-h22kokuchonenrei.html"
|-- META  /data 'od-h22kokuchonenrei  /name 'タイトル  /content "【平成22年国勢調査】区別男女別年齢別人口"
|-- META  /data 'od-h22kokuchonenrei  /name 'タグ  /content '国勢調査
|-- META  /data 'od-h22kokuchonenrei  /name 'ファイルサイズ  /content '12キロバイト

|-- META  /data 'od-h22kokuchonenrei  /name 'ライセンス  /content "CC-BY（表示）"
|-- META  /data 'od-h22kokuchonenrei  /name 'リリース日  /content '2015年7月2日
|-- META  /data 'od-h22kokuchonenrei  /name '作成者  /content '総務部総務課
|-- META  /data 'od-h22kokuchonenrei  /name '使用言語  /content "日本語・UTF-8"
|-- META  /data 'od-h22kokuchonenrei  /name '公表組織名  /content '新潟市

|-- META  /data 'od-h22kokuchonenrei  /name '最終更新日  /content '2015年7月2日
|-- META  /data 'od-h22kokuchonenrei  /name '補足1  /content "本ファイルは、平成22年10月1日実施の国勢調査結果に基づいた人口です。"
|-- META  /data 'od-h22kokuchonenrei  /name '補足2  /content "本ファイルには、世帯数の掲載はありません。"
|-- META  /data 'od-h22kokuchonenrei  /name '補足3  /content "本ファイルの「全年齢」には、「年齢不詳」を含みます。"
|-- META  /data 'od-h22kokuchonenrei  /name '調査日  /content "2010年（平成22年）10月1日"

|-- META  /data 'od-h22kokuchosetai  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-toukei/od-kokucho/od-h22kokuchou/od-h22kokuchosetai.html"
|-- META  /data 'od-h22kokuchosetai  /name 'タイトル  /content "【平成22年国勢調査】区・世帯の種類（2区分）・世帯人員（10区分）別世帯数及び世帯人員"
|-- META  /data 'od-h22kokuchosetai  /name 'タグ  /content '国勢調査
|-- META  /data 'od-h22kokuchosetai  /name 'ファイルサイズ  /content '1キロバイト
|-- META  /data 'od-h22kokuchosetai  /name 'ライセンス  /content "CC-BY（表示）"
*** 1000

|-- META  /data 'od-h22kokuchosetai  /name 'リリース日  /content '2015年7月2日
|-- META  /data 'od-h22kokuchosetai  /name '作成者  /content '総務部総務課
|-- META  /data 'od-h22kokuchosetai  /name '使用言語  /content "日本語・UTF-8"
|-- META  /data 'od-h22kokuchosetai  /name '公表組織名  /content '新潟市
|-- META  /data 'od-h22kokuchosetai  /name '最終更新日  /content '2015年7月2日

|-- META  /data 'od-h22kokuchosetai  /name '補足1  /content "本ファイルは、平成22年10月1日実施の国勢調査結果に基づいた世帯数及び世帯人員です。"
|-- META  /data 'od-h22kokuchosetai  /name '補足2  /content "本ファイルには、年齢別数値の掲載はありません。"
|-- META  /data 'od-h22kokuchosetai  /name '補足3  /content "本ファイルの「総世帯数」「総世帯人員」には、「不詳」を含みます。"
|-- META  /data 'od-h22kokuchosetai  /name '調査日  /content "2010年（平成22年）10月1日"
|-- META  /data 'od-h22kokuchosyugyo  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-toukei/od-kokucho/od-h22kokuchou/od-h22kokuchosyugyo.html"

|-- META  /data 'od-h22kokuchosyugyo  /name 'タイトル  /content "【平成22年国勢調査】区・産業（大分類）・男女別15歳以上就業者数"
|-- META  /data 'od-h22kokuchosyugyo  /name 'タグ  /content '国勢調査
|-- META  /data 'od-h22kokuchosyugyo  /name 'ファイルサイズ  /content '3キロバイト
|-- META  /data 'od-h22kokuchosyugyo  /name 'ライセンス  /content "CC-BY（表示）"
|-- META  /data 'od-h22kokuchosyugyo  /name 'リリース日  /content '2015年7月2日

|-- META  /data 'od-h22kokuchosyugyo  /name '作成者  /content '総務部総務課
|-- META  /data 'od-h22kokuchosyugyo  /name '使用言語  /content "日本語・UTF-8"
|-- META  /data 'od-h22kokuchosyugyo  /name '公表組織名  /content '新潟市
|-- META  /data 'od-h22kokuchosyugyo  /name '最終更新日  /content '2015年7月2日
|-- META  /data 'od-h22kokuchosyugyo  /name '補足1  /content "本ファイルは、平成22年10月1日実施の国勢調査結果に基づいた就業者数です。"

|-- META  /data 'od-h22kokuchosyugyo  /name '補足2  /content "本ファイルには、年齢別数値の掲載はありません。"
|-- META  /data 'od-h22kokuchosyugyo  /name '補足3  /content "本ファイルの「総数」には、「分類不能の産業」を含みます。"
|-- META  /data 'od-h22kokuchosyugyo  /name '調査日  /content "2010年（平成22年）10月1日"
|-- META  /data 'od-h25  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-toukei/od-jinkou/od-jyukijinkou/od-ku_danjo_nenrei/od-h25.html"
|-- META  /data 'od-h25  /name 'タイトル  /content "【住民基本台帳人口】区別男女別年齢別人口"
*** 1025

|-- META  /data 'od-h25  /name 'タグ  /content '人口
|-- META  /data 'od-h25  /name 'ファイルサイズ  /content '5キロバイト
|-- META  /data 'od-h25  /name 'ライセンス  /content "CC-BY（表示）"
|-- META  /data 'od-h25  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-h25  /name '作成者  /content '総務部総務課

|-- META  /data 'od-h25  /name '使用言語  /content "日本語・UTF-8"
|-- META  /data 'od-h25  /name '公表組織名  /content '新潟市
|-- META  /data 'od-h25  /name '更新頻度  /content '毎月
|-- META  /data 'od-h25  /name '最終更新日  /content '2014年12月4日
|-- META  /data 'od-h25  /name '補足1  /content "本ファイルは、住民基本台帳に基づく人口です。"

|-- META  /data 'od-h25  /name '補足2  /content "毎月末日現在の数値です。"
|-- META  /data 'od-h25  /name '補足3  /content "本ファイルには、世帯数の掲載はありません。"
|-- META  /data 'od-h26  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-toukei/od-jinkou/od-jyukijinkou/od-ku_danjo_nenrei/od-h26.html"
|-- META  /data 'od-h26  /name 'タイトル  /content "【住民基本台帳人口】区別男女別年齢別人口"
|-- META  /data 'od-h26  /name 'タグ  /content '人口

|-- META  /data 'od-h26  /name 'ファイルサイズ  /content '5キロバイト
|-- META  /data 'od-h26  /name 'ライセンス  /content "CC-BY（表示）"
|-- META  /data 'od-h26  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-h26  /name '作成者  /content '総務部総務課
|-- META  /data 'od-h26  /name '使用言語  /content "日本語・UTF-8"

|-- META  /data 'od-h26  /name '公表組織名  /content '新潟市
|-- META  /data 'od-h26  /name '更新頻度  /content '毎月
|-- META  /data 'od-h26  /name '最終更新日  /content '2015年1月9日
|-- META  /data 'od-h26  /name '補足1  /content "本ファイルは、住民基本台帳に基づく人口です。"
|-- META  /data 'od-h26  /name '補足2  /content "最新版は、平成26年12月31日現在の数値です。"
*** 1050

|-- META  /data 'od-h26  /name '補足3  /content "本ファイルには、世帯数の掲載はありません。"
|-- META  /data 'od-h27  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-toukei/od-jinkou/od-jyukijinkou/od-ku_danjo_nenrei/od-h27.html"
|-- META  /data 'od-h27  /name 'タイトル  /content "【住民基本台帳人口】区別男女別年齢別人口"
|-- META  /data 'od-h27  /name 'タグ  /content '人口
|-- META  /data 'od-h27  /name 'ファイルサイズ  /content '5キロバイト

|-- META  /data 'od-h27  /name 'ライセンス  /content "CC-BY（表示）"
|-- META  /data 'od-h27  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-h27  /name '作成者  /content '総務部総務課
|-- META  /data 'od-h27  /name '使用言語  /content "日本語・UTF-8"
|-- META  /data 'od-h27  /name '公表組織名  /content '新潟市

|-- META  /data 'od-h27  /name '更新頻度  /content '毎月
|-- META  /data 'od-h27  /name '最終更新日  /content '2015年7月8日
|-- META  /data 'od-h27  /name '補足1  /content "本ファイルは、住民基本台帳に基づく人口です。"
|-- META  /data 'od-h27  /name '補足2  /content "最新版は、平成27年6月30日現在の数値です。"
|-- META  /data 'od-h27  /name '補足3  /content "本ファイルには、世帯数の掲載はありません。"

|-- META  /data 'od-juki_syoumei_mado  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-tetsuduki/od-juki_syoumei_mado.html"
|-- META  /data 'od-juki_syoumei_mado  /name 'タイトル  /content "住民記録・戸籍系証明発行窓口一覧"
|-- META  /data 'od-juki_syoumei_mado  /name 'タグ  /content "くらし、手続き"
|-- META  /data 'od-juki_syoumei_mado  /name 'ファイルサイズ  /content '12キロバイト
|-- META  /data 'od-juki_syoumei_mado  /name 'ライセンス  /content "CC-BY（表示）"

|-- META  /data 'od-juki_syoumei_mado  /name 'リリース日  /content '2015年4月30日
|-- META  /data 'od-juki_syoumei_mado  /name '作成者  /content '市民生活部市民生活課
|-- META  /data 'od-juki_syoumei_mado  /name '使用言語  /content "日本語・UTF-8"
|-- META  /data 'od-juki_syoumei_mado  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-juki_syoumei_mado  /name '更新頻度  /content '随時
*** 1075

|-- META  /data 'od-juki_syoumei_mado  /name '最終更新日  /content '2015年4月30日
|-- META  /data 'od-juki_syoumei_mado  /name '組織名  /content '新潟市
|-- META  /data 'od-juki_todoke_mado  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-tetsuduki/od-juki_todoke_mado.html"
|-- META  /data 'od-juki_todoke_mado  /name 'タイトル  /content "住民記録・戸籍系届出窓口一覧"
|-- META  /data 'od-juki_todoke_mado  /name 'タグ  /content "くらし、手続き"

|-- META  /data 'od-juki_todoke_mado  /name 'ファイルサイズ  /content '12キロバイト
|-- META  /data 'od-juki_todoke_mado  /name 'ライセンス  /content "CC-BY（表示）"
|-- META  /data 'od-juki_todoke_mado  /name 'リリース日  /content '2015年4月30日
|-- META  /data 'od-juki_todoke_mado  /name '作成者  /content '市民生活部市民生活課
|-- META  /data 'od-juki_todoke_mado  /name '使用言語  /content "日本語・UTF-8"

|-- META  /data 'od-juki_todoke_mado  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-juki_todoke_mado  /name '更新頻度  /content '随時
|-- META  /data 'od-juki_todoke_mado  /name '最終更新日  /content '2015年4月30日
|-- META  /data 'od-juki_todoke_mado  /name '組織名  /content '新潟市
|-- META  /data 'od-koutsu001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-koutsu/od-koutsu001.html"

|-- META  /data 'od-koutsu001  /name 'タイトル  /content 'ときめき橋
|-- META  /data 'od-koutsu001  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-koutsu001  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-koutsu001  /name '公表組織名  /content '新潟市
|-- META  /data 'od-koutsu001  /name '地域  /content '新潟市

|-- META  /data 'od-koutsu001  /name '実効画像サイズ  /content "幅2956×高さ4450（ピクセル）"
|-- META  /data 'od-koutsu001  /name '撮影日  /content '2007年
|-- META  /data 'od-koutsu001  /name '更新頻度  /content '不定期
|-- META  /data 'od-koutsu001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-koutsu002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-koutsu/od-koutsu002.html"
*** 1100

|-- META  /data 'od-koutsu002  /name 'タイトル  /content 'はさ木並木と農道
|-- META  /data 'od-koutsu002  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-koutsu002  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-koutsu002  /name '公表組織名  /content '新潟市
|-- META  /data 'od-koutsu002  /name '地域  /content '新潟市秋葉区満願寺

|-- META  /data 'od-koutsu002  /name '実効画像サイズ  /content "幅3264×高さ2448（ピクセル）"
|-- META  /data 'od-koutsu002  /name '撮影日  /content '2013年9月14日
|-- META  /data 'od-koutsu002  /name '撮影時刻  /content '午前9時43分
|-- META  /data 'od-koutsu002  /name '更新頻度  /content '不定期
|-- META  /data 'od-koutsu002  /name "言語・文字コード"  /content "日本語・UTF-8"

|-- META  /data 'od-koutsu003  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-koutsu/od-koutsu003.html"
|-- META  /data 'od-koutsu003  /name 'タイトル  /content '新潟島一周自転車道
|-- META  /data 'od-koutsu003  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-koutsu003  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-koutsu003  /name '公表組織名  /content '新潟市

|-- META  /data 'od-koutsu003  /name '地域  /content '新潟市中央区川端町
|-- META  /data 'od-koutsu003  /name '実効画像サイズ  /content "幅3456×高さ2304（ピクセル）"
|-- META  /data 'od-koutsu003  /name '撮影日  /content '2012年6月7日
|-- META  /data 'od-koutsu003  /name '撮影時刻  /content '午後2時46分
|-- META  /data 'od-koutsu003  /name '更新頻度  /content '不定期

|-- META  /data 'od-koutsu003  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-kubetsujyuki  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-toukei/od-jinkou/od-jyukijinkou/od-kubetsujyuki.html"
|-- META  /data 'od-kubetsujyuki  /name 'タイトル  /content "【住民基本台帳人口】区別男女別人口及び世帯数"
|-- META  /data 'od-kubetsujyuki  /name 'タグ  /content '人口
|-- META  /data 'od-kubetsujyuki  /name 'ファイルサイズ  /content '0.8キロバイト
*** 1125

|-- META  /data 'od-kubetsujyuki  /name 'ライセンス  /content "CC-BY（表示）"
|-- META  /data 'od-kubetsujyuki  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-kubetsujyuki  /name '作成者  /content '総務部総務課
|-- META  /data 'od-kubetsujyuki  /name '使用言語  /content "日本語・UTF-8"
|-- META  /data 'od-kubetsujyuki  /name '公表組織名  /content '新潟市

|-- META  /data 'od-kubetsujyuki  /name '更新頻度  /content '毎月
|-- META  /data 'od-kubetsujyuki  /name '最終更新日  /content '2015年7月8日
|-- META  /data 'od-kubetsujyuki  /name '補足1  /content "本ファイルは、住民基本台帳に基づく人口及び世帯数です。"
|-- META  /data 'od-kubetsujyuki  /name '補足2  /content "最新版は、平成27年6月31日現在の数値です。"
|-- META  /data 'od-kubetsujyuki  /name '補足3  /content "本ファイルには、年齢別数値の掲載はありません。"

|-- META  /data 'od-kubetsujyuki  /name '補足4  /content "数値には、転出予定者を含んでおりません。"
|-- META  /data 'od-kuusatsu001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-kuusatsu/od-kuusatsu001.html"
|-- META  /data 'od-kuusatsu001  /name 'タイトル  /content '新潟市街と田園
|-- META  /data 'od-kuusatsu001  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-kuusatsu001  /name '作成者  /content "地域・魅力創造部広報課"

|-- META  /data 'od-kuusatsu001  /name '公表組織名  /content '新潟市
|-- META  /data 'od-kuusatsu001  /name '地域  /content '新潟市
|-- META  /data 'od-kuusatsu001  /name '実効画像サイズ  /content "幅4256×高さ2764（ピクセル）"
|-- META  /data 'od-kuusatsu001  /name '撮影日  /content '2008年
|-- META  /data 'od-kuusatsu001  /name '更新頻度  /content '不定期

|-- META  /data 'od-kuusatsu001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-kuusatsu002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-kuusatsu/od-kuusatsu002.html"
|-- META  /data 'od-kuusatsu002  /name 'タイトル  /content '新潟のまち
|-- META  /data 'od-kuusatsu002  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-kuusatsu002  /name '作成者  /content "地域・魅力創造部広報課"
*** 1150

|-- META  /data 'od-kuusatsu002  /name '公表者組織名  /content '新潟市
|-- META  /data 'od-kuusatsu002  /name '地域  /content '新潟市
|-- META  /data 'od-kuusatsu002  /name '実効画像サイズ  /content "幅8173×高さ4204（ピクセル）"
|-- META  /data 'od-kuusatsu002  /name '撮影日  /content '2007年
|-- META  /data 'od-kuusatsu002  /name '更新頻度  /content '不定期

|-- META  /data 'od-kuusatsu002  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-kuusatsu003  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-kuusatsu/od-kuusatsu003.html"
|-- META  /data 'od-kuusatsu003  /name 'タイトル  /content '越後平野
|-- META  /data 'od-kuusatsu003  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-kuusatsu003  /name '作成者  /content "地域・魅力創造部広報課"

|-- META  /data 'od-kuusatsu003  /name '公表組織名  /content '新潟市
|-- META  /data 'od-kuusatsu003  /name '地域  /content '新潟市
|-- META  /data 'od-kuusatsu003  /name '実効画像サイズ  /content "幅4368×高さ2912（ピクセル）"
|-- META  /data 'od-kuusatsu003  /name '撮影日  /content '2006年
|-- META  /data 'od-kuusatsu003  /name '更新頻度  /content '不定期

|-- META  /data 'od-kuusatsu003  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-kyusaitouke001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-bunkashisetsu/od-kyusaitouke/od-kyusaitouke001.html"
|-- META  /data 'od-kyusaitouke001  /name 'タイトル  /content '旧齋藤家別邸1
|-- META  /data 'od-kyusaitouke001  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-kyusaitouke001  /name '住所  /content '新潟市中央区西大畑町576番地

|-- META  /data 'od-kyusaitouke001  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-kyusaitouke001  /name '公表組織名  /content '新潟市
|-- META  /data 'od-kyusaitouke001  /name '実効画像サイズ  /content "幅1416×高さ2128（ピクセル）"
|-- META  /data 'od-kyusaitouke001  /name '撮影日  /content '2009年6月
|-- META  /data 'od-kyusaitouke001  /name '更新頻度  /content '不定期
*** 1175

|-- META  /data 'od-kyusaitouke001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-kyusaitouke002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-bunkashisetsu/od-kyusaitouke/od-kyusaitouke002.html"
|-- META  /data 'od-kyusaitouke002  /name 'タイトル  /content '旧齋藤家別邸2
|-- META  /data 'od-kyusaitouke002  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-kyusaitouke002  /name '住所  /content '新潟市中央区西大畑町576番地

|-- META  /data 'od-kyusaitouke002  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-kyusaitouke002  /name '公表組織名  /content '新潟市
|-- META  /data 'od-kyusaitouke002  /name '実効画像サイズ  /content "幅2128×高さ1416（ピクセル）"
|-- META  /data 'od-kyusaitouke002  /name '撮影日  /content '2009年6月
|-- META  /data 'od-kyusaitouke002  /name '更新頻度  /content '不定期

|-- META  /data 'od-kyusaitouke002  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-kyusaitouke003  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-bunkashisetsu/od-kyusaitouke/od-kyusaitouke003.html"
|-- META  /data 'od-kyusaitouke003  /name 'タイトル  /content '旧齋藤家別邸3
|-- META  /data 'od-kyusaitouke003  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-kyusaitouke003  /name '住所  /content '新潟市中央区西大畑町576番地

|-- META  /data 'od-kyusaitouke003  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-kyusaitouke003  /name '公表組織名  /content '新潟市
|-- META  /data 'od-kyusaitouke003  /name '実効画像サイズ  /content "幅4256×高さ2832（ピクセル）"
|-- META  /data 'od-kyusaitouke003  /name '撮影日  /content '2009年6月
|-- META  /data 'od-kyusaitouke003  /name '更新頻度  /content '不定期

|-- META  /data 'od-kyusaitouke003  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-kyuzeikan001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-bunkashisetsu/od-kyuzeikan/od-kyuzeikan001.html"
|-- META  /data 'od-kyuzeikan001  /name 'タイトル  /content '旧新潟税関庁舎4
|-- META  /data 'od-kyuzeikan001  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-kyuzeikan001  /name '住所  /content '新潟市中央区柳島町2丁目10番地
*** 1200

|-- META  /data 'od-kyuzeikan001  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-kyuzeikan001  /name '公表組織名  /content '新潟市
|-- META  /data 'od-kyuzeikan001  /name '実効画像サイズ  /content "幅2722×高さ1814（ピクセル）"
|-- META  /data 'od-kyuzeikan001  /name '撮影日  /content '2010年
|-- META  /data 'od-kyuzeikan001  /name '更新頻度  /content '不定期

|-- META  /data 'od-kyuzeikan001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-kyuzeikan002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-bunkashisetsu/od-kyuzeikan/od-kyuzeikan002.html"
|-- META  /data 'od-kyuzeikan002  /name 'タイトル  /content '旧新潟税関庁舎2
|-- META  /data 'od-kyuzeikan002  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-kyuzeikan002  /name '住所  /content '新潟市中央区柳島町2丁目10番地

|-- META  /data 'od-kyuzeikan002  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-kyuzeikan002  /name '公表組織名  /content '新潟市
|-- META  /data 'od-kyuzeikan002  /name '実効画像サイズ  /content "幅350×高さ350（ピクセル）"
|-- META  /data 'od-kyuzeikan002  /name '撮影日  /content '2010年
|-- META  /data 'od-kyuzeikan002  /name '更新頻度  /content '不定期

|-- META  /data 'od-kyuzeikan002  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-kyuzeikan003  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-bunkashisetsu/od-kyuzeikan/od-kyuzeikan003.html"
|-- META  /data 'od-kyuzeikan003  /name 'タイトル  /content '旧新潟税関庁舎3
|-- META  /data 'od-kyuzeikan003  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-kyuzeikan003  /name '住所  /content '新潟市中央区柳島町2丁目10番地

|-- META  /data 'od-kyuzeikan003  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-kyuzeikan003  /name '公表組織名  /content '新潟市
|-- META  /data 'od-kyuzeikan003  /name '実効画像サイズ  /content "幅1555×高さ1037（ピクセル）"
|-- META  /data 'od-kyuzeikan003  /name '撮影日  /content '2010年
|-- META  /data 'od-kyuzeikan003  /name '更新頻度  /content '不定期
*** 1225

|-- META  /data 'od-kyuzeikan003  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-kyuzeikan004  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-bunkashisetsu/od-kyuzeikan/od-kyuzeikan004.html"
|-- META  /data 'od-kyuzeikan004  /name 'タイトル  /content '旧新潟税関庁舎4
|-- META  /data 'od-kyuzeikan004  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-kyuzeikan004  /name '住所  /content '新潟市中央区柳島町2丁目10番地

|-- META  /data 'od-kyuzeikan004  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-kyuzeikan004  /name '公表組織名  /content '新潟市
|-- META  /data 'od-kyuzeikan004  /name '実効画像サイズ  /content "幅1522×高さ1015（ピクセル）"
|-- META  /data 'od-kyuzeikan004  /name '撮影日  /content '2007年4月
|-- META  /data 'od-kyuzeikan004  /name '更新頻度  /content '不定期

|-- META  /data 'od-kyuzeikan004  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-machinami001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-machinami/od-machinami001.html"
|-- META  /data 'od-machinami001  /name 'タイトル  /content '萬代橋と新潟市街
|-- META  /data 'od-machinami001  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-machinami001  /name '作成者  /content "地域・魅力創造部広報課"

|-- META  /data 'od-machinami001  /name '公表組織名  /content '新潟市
|-- META  /data 'od-machinami001  /name '地域  /content '新潟市中央区万代
|-- META  /data 'od-machinami001  /name '実効画像サイズ  /content "幅3209×高さ4814（ピクセル）"
|-- META  /data 'od-machinami001  /name '撮影日  /content '2013年
|-- META  /data 'od-machinami001  /name '更新頻度  /content '不定期

|-- META  /data 'od-machinami001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-machinami002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-machinami/od-machinami002.html"
|-- META  /data 'od-machinami002  /name 'タイトル  /content 'まき鯛車商店街
|-- META  /data 'od-machinami002  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-machinami002  /name '作成者  /content "地域・魅力創造部広報課"
*** 1250

|-- META  /data 'od-machinami002  /name '公表組織名  /content '新潟市
|-- META  /data 'od-machinami002  /name '地域  /content '新潟市西蒲区巻
|-- META  /data 'od-machinami002  /name '実効画像サイズ  /content "幅2745×高さ1819（ピクセル）"
|-- META  /data 'od-machinami002  /name '撮影日  /content '2013年
|-- META  /data 'od-machinami002  /name '更新頻度  /content '不定期

|-- META  /data 'od-machinami002  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-machinami003  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-machinami/od-machinami003.html"
|-- META  /data 'od-machinami003  /name 'タイトル  /content '新潟市街と信濃川
|-- META  /data 'od-machinami003  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-machinami003  /name '作成者  /content "地域・魅力創造部広報課"

|-- META  /data 'od-machinami003  /name '公表組織名  /content '新潟市
|-- META  /data 'od-machinami003  /name '地域  /content '新潟市中央区万代島
|-- META  /data 'od-machinami003  /name '実効画像サイズ  /content "幅8040×高さ5340（ピクセル）"
|-- META  /data 'od-machinami003  /name '撮影日  /content '2006年
|-- META  /data 'od-machinami003  /name '更新頻度  /content '不定期

|-- META  /data 'od-machinami003  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-machinami004  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-machinami/od-machinami004.html"
|-- META  /data 'od-machinami004  /name 'タイトル  /content '新潟駅南口広場1
|-- META  /data 'od-machinami004  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-machinami004  /name '作成者  /content "地域・魅力創造部広報課"

|-- META  /data 'od-machinami004  /name '公表組織名  /content '新潟市
|-- META  /data 'od-machinami004  /name '地域  /content '新潟市中央区花園
|-- META  /data 'od-machinami004  /name '実効画像サイズ  /content "幅4752×高さ3168（ピクセル）"
|-- META  /data 'od-machinami004  /name '撮影日  /content '2013年9月3日
|-- META  /data 'od-machinami004  /name '撮影時刻  /content '午後2時2分
*** 1275

|-- META  /data 'od-machinami004  /name '更新頻度  /content '不定期
|-- META  /data 'od-machinami004  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-machinami005  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-machinami/od-machinami005.html"
|-- META  /data 'od-machinami005  /name 'タイトル  /content '新潟駅南口広場2
|-- META  /data 'od-machinami005  /name 'ライセンス  /content "表示（CC-BY）"

|-- META  /data 'od-machinami005  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-machinami005  /name '公表組織名  /content '新潟市
|-- META  /data 'od-machinami005  /name '地域  /content '新潟市中央区花園
|-- META  /data 'od-machinami005  /name '実効画像サイズ  /content "幅4752×高さ3168（ピクセル）"
|-- META  /data 'od-machinami005  /name '撮影日  /content '2013年9月3日

|-- META  /data 'od-machinami005  /name '撮影時刻  /content '午後2時2分
|-- META  /data 'od-machinami005  /name '更新頻度  /content '不定期
|-- META  /data 'od-machinami005  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-machinami006  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-machinami/od-machinami006.html"
|-- META  /data 'od-machinami006  /name 'タイトル  /content '新潟駅南口広場3

|-- META  /data 'od-machinami006  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-machinami006  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-machinami006  /name '公表組織名  /content '新潟市
|-- META  /data 'od-machinami006  /name '地域  /content '新潟市中央区花園
|-- META  /data 'od-machinami006  /name '実効画像サイズ  /content "幅4752×高さ3168（ピクセル）"

|-- META  /data 'od-machinami006  /name '撮影日  /content '2013年9月3日
|-- META  /data 'od-machinami006  /name '撮影時刻  /content '午後2時41分
|-- META  /data 'od-machinami006  /name '更新頻度  /content '不定期
|-- META  /data 'od-machinami006  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-minato001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-minato/od-minato001.html"
*** 1300

|-- META  /data 'od-minato001  /name 'タイトル  /content '柳都大橋から見た新潟西港1
|-- META  /data 'od-minato001  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-minato001  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-minato001  /name '地域  /content '新潟市中央区万代
|-- META  /data 'od-minato001  /name '実効画像サイズ  /content "幅3744×高さ5616（ピクセル）"

|-- META  /data 'od-minato001  /name '撮影日  /content '2010年
|-- META  /data 'od-minato001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-minato002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-minato/od-minato002.html"
|-- META  /data 'od-minato002  /name 'タイトル  /content '船上から見た新潟西港
|-- META  /data 'od-minato002  /name 'ライセンス  /content "表示（CC-BY）"

|-- META  /data 'od-minato002  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-minato002  /name '地域  /content '新潟市
|-- META  /data 'od-minato002  /name '実効画像サイズ  /content "幅5616×高さ3744（ピクセル）"
|-- META  /data 'od-minato002  /name '撮影日  /content '2010年
|-- META  /data 'od-minato002  /name "言語・文字コード"  /content "日本語・UTF-8"

|-- META  /data 'od-minato003  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-minato/od-minato003.html"
|-- META  /data 'od-minato003  /name 'タイトル  /content '万代島から見た新潟西港
|-- META  /data 'od-minato003  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-minato003  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-minato003  /name '地域  /content '新潟市中央区万代島

|-- META  /data 'od-minato003  /name '実効画像サイズ  /content "幅4752×高さ3168（ピクセル）"
|-- META  /data 'od-minato003  /name '撮影日  /content '2014年7月30日
|-- META  /data 'od-minato003  /name '撮影時刻  /content '午後1時19分
|-- META  /data 'od-minato003  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-minato004  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-minato/od-minato004.html"
*** 1325

|-- META  /data 'od-minato004  /name 'タイトル  /content '新潟西港とフェリー1
|-- META  /data 'od-minato004  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-minato004  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-minato004  /name '地域  /content '新潟市中央区万代
|-- META  /data 'od-minato004  /name '実効画像サイズ  /content "幅3264×高さ2448（ピクセル）"

|-- META  /data 'od-minato004  /name '撮影日  /content '2013年12月4日
|-- META  /data 'od-minato004  /name '撮影時刻  /content '午前9時31分
|-- META  /data 'od-minato004  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-minato005  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-minato/od-minato005.html"
|-- META  /data 'od-minato005  /name 'タイトル  /content '新潟西港とフェリー2

|-- META  /data 'od-minato005  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-minato005  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-minato005  /name '地域  /content '新潟市中央区万代
|-- META  /data 'od-minato005  /name '実効画像サイズ  /content "幅3264×高さ2448（ピクセル）"
|-- META  /data 'od-minato005  /name '撮影日  /content '2013年12月4日

|-- META  /data 'od-minato005  /name '撮影時刻  /content '午前9時27分
|-- META  /data 'od-minato005  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-minato006  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-minato/od-minato006.html"
|-- META  /data 'od-minato006  /name 'タイトル  /content '柳都大橋から見た新潟西港2
|-- META  /data 'od-minato006  /name 'ライセンス  /content "表示（CC-BY）"

|-- META  /data 'od-minato006  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-minato006  /name '地域  /content '新潟市中央区万代
|-- META  /data 'od-minato006  /name '実効画像サイズ  /content "幅3264×高さ2448（ピクセル）"
|-- META  /data 'od-minato006  /name '撮影日  /content '2013年12月4日
|-- META  /data 'od-minato006  /name '撮影時刻  /content '午前9時26分
*** 1350

|-- META  /data 'od-minato006  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-minatopia001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-bunkashisetsu/od-minatopia/od-minatopia001.html"
|-- META  /data 'od-minatopia001  /name 'タイトル  /content 'みなとぴあ1
|-- META  /data 'od-minatopia001  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-minatopia001  /name '住所  /content '新潟市中央区柳島町2丁目10番地

|-- META  /data 'od-minatopia001  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-minatopia001  /name '公表組織名  /content '新潟市
|-- META  /data 'od-minatopia001  /name '実効画像サイズ  /content "幅5031×高さ3345（ピクセル）"
|-- META  /data 'od-minatopia001  /name '撮影日  /content '2012年5月
|-- META  /data 'od-minatopia001  /name '更新頻度  /content '不定期

|-- META  /data 'od-minatopia001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-minatopia002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-bunkashisetsu/od-minatopia/od-minatopia002.html"
|-- META  /data 'od-minatopia002  /name 'タイトル  /content 'みなとぴあ2
|-- META  /data 'od-minatopia002  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-minatopia002  /name '住所  /content '新潟市中央区柳島町2丁目10番地

|-- META  /data 'od-minatopia002  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-minatopia002  /name '公表組織名  /content '新潟市
|-- META  /data 'od-minatopia002  /name '実効画像サイズ  /content "幅1776×高さ1181（ピクセル）"
|-- META  /data 'od-minatopia002  /name '撮影日  /content '2011年
|-- META  /data 'od-minatopia002  /name '更新頻度  /content '不定期

|-- META  /data 'od-minatopia002  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-minatopia003  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-bunkashisetsu/od-minatopia/od-minatopia003.html"
|-- META  /data 'od-minatopia003  /name 'タイトル  /content 'みなとぴあ3
|-- META  /data 'od-minatopia003  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-minatopia003  /name '住所  /content '新潟市中央区柳島町2丁目10番地
*** 1375

|-- META  /data 'od-minatopia003  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-minatopia003  /name '公表組織名  /content '新潟市
|-- META  /data 'od-minatopia003  /name '実効画像サイズ  /content "幅5184×高さ3456（ピクセル）"
|-- META  /data 'od-minatopia003  /name '撮影日  /content '2013年12月8日
|-- META  /data 'od-minatopia003  /name '撮影時刻  /content '午前11時47分

|-- META  /data 'od-minatopia003  /name '更新頻度  /content '不定期
|-- META  /data 'od-minatopia003  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-minatopia004  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-bunkashisetsu/od-minatopia/od-minatopia004.html"
|-- META  /data 'od-minatopia004  /name 'タイトル  /content 'みなとぴあ4
|-- META  /data 'od-minatopia004  /name 'ライセンス  /content "表示（CC-BY）"

|-- META  /data 'od-minatopia004  /name '住所  /content '新潟市中央区柳島町2丁目10番地
|-- META  /data 'od-minatopia004  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-minatopia004  /name '公表組織名  /content '新潟市
|-- META  /data 'od-minatopia004  /name '実効画像サイズ  /content "幅3456×高さ2304（ピクセル）"
|-- META  /data 'od-minatopia004  /name '撮影日  /content '2012年9月1日

|-- META  /data 'od-minatopia004  /name '撮影時刻  /content '午前11時3分
|-- META  /data 'od-minatopia004  /name '更新頻度  /content '不定期
|-- META  /data 'od-minatopia004  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-minatopia005  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-bunkashisetsu/od-minatopia/od-minatopia005.html"
|-- META  /data 'od-minatopia005  /name 'タイトル  /content 'みなとぴあ5

|-- META  /data 'od-minatopia005  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-minatopia005  /name '住所  /content '新潟市中央区柳島町2丁目10番地
|-- META  /data 'od-minatopia005  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-minatopia005  /name '公表組織名  /content '新潟市
|-- META  /data 'od-minatopia005  /name '実効画像サイズ  /content "幅3456×高さ2304（ピクセル）"
*** 1400

|-- META  /data 'od-minatopia005  /name '撮影日  /content '2012年9月1日
|-- META  /data 'od-minatopia005  /name '撮影時刻  /content '午前11時4分
|-- META  /data 'od-minatopia005  /name '更新頻度  /content '不定期
|-- META  /data 'od-minatopia005  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-minatopia006  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-bunkashisetsu/od-minatopia/od-minatopia006.html"

|-- META  /data 'od-minatopia006  /name 'タイトル  /content 'みなとぴあ6
|-- META  /data 'od-minatopia006  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-minatopia006  /name '住所  /content '新潟市中央区柳島町2丁目10番地
|-- META  /data 'od-minatopia006  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-minatopia006  /name '公表組織名  /content '新潟市

|-- META  /data 'od-minatopia006  /name '実効画像サイズ  /content "幅3456×高さ2304（ピクセル）"
|-- META  /data 'od-minatopia006  /name '撮影日  /content '2012年9月1日
|-- META  /data 'od-minatopia006  /name '撮影時刻  /content '午前11時8分
|-- META  /data 'od-minatopia006  /name '更新頻度  /content '不定期
|-- META  /data 'od-minatopia006  /name "言語・文字コード"  /content "日本語・UTF-8"

|-- META  /data 'od-minatopia007  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-bunkashisetsu/od-minatopia/od-minatopia007.html"
|-- META  /data 'od-minatopia007  /name 'タイトル  /content 'みなとぴあ7
|-- META  /data 'od-minatopia007  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-minatopia007  /name '住所  /content '新潟市中央区柳島町2丁目10番地
|-- META  /data 'od-minatopia007  /name '作成者  /content "地域・魅力創造部広報課"

|-- META  /data 'od-minatopia007  /name '公表組織名  /content '新潟市
|-- META  /data 'od-minatopia007  /name '実効画像サイズ  /content "幅3264×高さ2448（ピクセル）"
|-- META  /data 'od-minatopia007  /name '撮影日  /content '2013年12月4日
|-- META  /data 'od-minatopia007  /name '撮影時刻  /content '午前8時48分
|-- META  /data 'od-minatopia007  /name '更新頻度  /content '不定期
*** 1425

|-- META  /data 'od-minatopia007  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-mizu  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-toukei/od-kankyo/od-mizukankyo/od-mizu.html"
|-- META  /data 'od-mizu  /name 'タイトル  /content '公共用水域水質測定結果
|-- META  /data 'od-mizu  /name 'ライセンス  /content "CC-BY（表示）"
|-- META  /data 'od-mizu  /name '作成者  /content '環境部環境対策課

|-- META  /data 'od-mizu  /name '使用言語  /content "日本語・UTF-8"
|-- META  /data 'od-mizu  /name '公表組織名  /content '新潟市
|-- META  /data 'od-mizu  /name '更新頻度  /content '毎年
|-- META  /data 'od-nihonkai001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-nihonkai/od-nihonkai001.html"
|-- META  /data 'od-nihonkai001  /name 'タイトル  /content '角田浜

|-- META  /data 'od-nihonkai001  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-nihonkai001  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-nihonkai001  /name '地域  /content '新潟市西蒲区角田浜
|-- META  /data 'od-nihonkai001  /name '実効画像サイズ  /content "幅3264×高さ2448（ピクセル）"
|-- META  /data 'od-nihonkai001  /name '撮影日  /content '2012年10月14日

|-- META  /data 'od-nihonkai001  /name '撮影時刻  /content '午前11時23分
|-- META  /data 'od-nihonkai001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-nihonkai002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-nihonkai/od-nihonkai002.html"
|-- META  /data 'od-nihonkai002  /name 'タイトル  /content '日和山浜
|-- META  /data 'od-nihonkai002  /name 'ライセンス  /content "表示（CC-BY）"

|-- META  /data 'od-nihonkai002  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-nihonkai002  /name '地域  /content '新潟市西蒲区角田浜
|-- META  /data 'od-nihonkai002  /name '実効画像サイズ  /content "幅3264×高さ2448（ピクセル）"
|-- META  /data 'od-nihonkai002  /name '撮影日  /content '2013年6月30日
|-- META  /data 'od-nihonkai002  /name '撮影時刻  /content '午後2時49分
*** 1450

|-- META  /data 'od-nihonkai002  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-nihonkai003  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-nihonkai/od-nihonkai003.html"
|-- META  /data 'od-nihonkai003  /name 'タイトル  /content '間瀬海岸
|-- META  /data 'od-nihonkai003  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-nihonkai003  /name "公表者・作成者"  /content "地域・魅力創造部広報課"

|-- META  /data 'od-nihonkai003  /name '地域  /content '新潟市西蒲区間瀬
|-- META  /data 'od-nihonkai003  /name '実効画像サイズ  /content "幅3264×高さ2448（ピクセル）"
|-- META  /data 'od-nihonkai003  /name '撮影日  /content '2013年11月24日
|-- META  /data 'od-nihonkai003  /name '撮影時刻  /content '午前11時12分
|-- META  /data 'od-nihonkai003  /name "言語・文字コード"  /content "日本語・UTF-8"

|-- META  /data 'od-nihonkai004  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-nihonkai/od-nihonkai004.html"
|-- META  /data 'od-nihonkai004  /name 'タイトル  /content '角田岬
|-- META  /data 'od-nihonkai004  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-nihonkai004  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-nihonkai004  /name '地域  /content '新潟市西蒲区五ケ浜

|-- META  /data 'od-nihonkai004  /name '実効画像サイズ  /content "幅3504×高さ2336（ピクセル）"
|-- META  /data 'od-nihonkai004  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-nihonkai006  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-nihonkai/od-nihonkai006.html"
|-- META  /data 'od-nihonkai006  /name 'タイトル  /content '寄居浜
|-- META  /data 'od-nihonkai006  /name 'ライセンス  /content "表示（CC-BY）"

|-- META  /data 'od-nihonkai006  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-nihonkai006  /name '地域  /content '新潟市中央区窪田町
|-- META  /data 'od-nihonkai006  /name '実効画像サイズ  /content "幅5184×高さ3456（ピクセル）"
|-- META  /data 'od-nihonkai006  /name '撮影日  /content '2014年10月7日
|-- META  /data 'od-nihonkai006  /name '撮影時刻  /content '午後2時7分
*** 1475

|-- META  /data 'od-nihonkai006  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-oto  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-toukei/od-kankyo/od-otokankyo/od-oto.html"
|-- META  /data 'od-oto  /name 'タイトル  /content '一般地域騒音調査結果
|-- META  /data 'od-oto  /name 'ライセンス  /content "CC-BY（表示）"
|-- META  /data 'od-oto  /name '作成者  /content '環境部環境対策課

|-- META  /data 'od-oto  /name '使用言語  /content "日本語・UTF-8"
|-- META  /data 'od-oto  /name '公表組織名  /content '新潟市
|-- META  /data 'od-oto  /name '更新頻度  /content '毎年
|-- META  /data 'od-river001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-river/od-river001.html"
|-- META  /data 'od-river001  /name 'タイトル  /content '信濃川とやすらぎ堤

|-- META  /data 'od-river001  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-river001  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-river001  /name '公表組織名  /content '新潟市
|-- META  /data 'od-river001  /name '地域  /content '新潟市中央区万代
|-- META  /data 'od-river001  /name '実効画像サイズ  /content "幅1555×高さ2333（ピクセル）"

|-- META  /data 'od-river001  /name '撮影日  /content '2009年
|-- META  /data 'od-river001  /name '更新頻度  /content '不定期
|-- META  /data 'od-river001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-river002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-river/od-river002.html"
|-- META  /data 'od-river002  /name 'タイトル  /content '船上から見た信濃川河口

|-- META  /data 'od-river002  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-river002  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-river002  /name '公表組織名  /content '新潟市
|-- META  /data 'od-river002  /name '地域  /content '新潟市
|-- META  /data 'od-river002  /name '実効画像サイズ  /content "幅4814×高さ3209（ピクセル）"
*** 1500

|-- META  /data 'od-river002  /name '更新頻度  /content '不定期
|-- META  /data 'od-river002  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-river003  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-river/od-river003.html"
|-- META  /data 'od-river003  /name 'タイトル  /content '信濃川と柳都大橋1
|-- META  /data 'od-river003  /name 'ライセンス  /content "表示（CC-BY）"

|-- META  /data 'od-river003  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-river003  /name '公表組織名  /content '新潟市
|-- META  /data 'od-river003  /name '地域  /content '新潟市中央区万代
|-- META  /data 'od-river003  /name '実効画像サイズ  /content "幅6000×高さ4000（ピクセル）"
|-- META  /data 'od-river003  /name '撮影日  /content '2014年9月20日

|-- META  /data 'od-river003  /name '撮影時刻  /content '午後1時22分
|-- META  /data 'od-river003  /name '更新頻度  /content '不定期
|-- META  /data 'od-river003  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-river004  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-river/od-river004.html"
|-- META  /data 'od-river004  /name 'タイトル  /content '信濃川と柳都大橋2

|-- META  /data 'od-river004  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-river004  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-river004  /name '公表組織名  /content '新潟市
|-- META  /data 'od-river004  /name '地域  /content '新潟市中央区万代
|-- META  /data 'od-river004  /name '実効画像サイズ  /content "幅6000×高さ4000（ピクセル）"

|-- META  /data 'od-river004  /name '撮影日  /content '2014年9月20日
|-- META  /data 'od-river004  /name '撮影時刻  /content '午後1時22分
|-- META  /data 'od-river004  /name '更新頻度  /content '不定期
|-- META  /data 'od-river004  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-river005  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-river/od-river005.html"
*** 1525

|-- META  /data 'od-river005  /name 'タイトル  /content '信濃川と柳都大橋3
|-- META  /data 'od-river005  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-river005  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-river005  /name '公表組織名  /content '新潟市
|-- META  /data 'od-river005  /name '地域  /content '新潟市中央区万代

|-- META  /data 'od-river005  /name '実効画像サイズ  /content "幅6000×高さ4000（ピクセル）"
|-- META  /data 'od-river005  /name '撮影日  /content '2014年9月20日
|-- META  /data 'od-river005  /name '撮影時刻  /content '午後1時25分
|-- META  /data 'od-river005  /name '更新頻度  /content '不定期
|-- META  /data 'od-river005  /name "言語・文字コード"  /content "日本語・UTF-8"

|-- META  /data 'od-river006  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-river/od-river006.html"
|-- META  /data 'od-river006  /name 'タイトル  /content '信濃川と柳都大橋4
|-- META  /data 'od-river006  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-river006  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-river006  /name '公表組織名  /content '新潟市

|-- META  /data 'od-river006  /name '地域  /content '新潟市中央区万代
|-- META  /data 'od-river006  /name '実効画像サイズ  /content "幅6000×高さ4000（ピクセル）"
|-- META  /data 'od-river006  /name '撮影日  /content '2014年9月20日
|-- META  /data 'od-river006  /name '撮影時刻  /content '午後1時25分
|-- META  /data 'od-river006  /name '更新頻度  /content '不定期

|-- META  /data 'od-river006  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-river007  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-river/od-river007.html"
|-- META  /data 'od-river007  /name 'タイトル  /content '信濃川と柳都大橋5
|-- META  /data 'od-river007  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-river007  /name '作成者  /content "地域・魅力創造部広報課"
*** 1550

|-- META  /data 'od-river007  /name '公表組織名  /content '新潟市
|-- META  /data 'od-river007  /name '地域  /content '新潟市中央区万代島
|-- META  /data 'od-river007  /name '実効画像サイズ  /content "幅4752×高さ3168（ピクセル）"
|-- META  /data 'od-river007  /name '撮影日  /content '2014年7月30日
|-- META  /data 'od-river007  /name '撮影時刻  /content '午後1時15分

|-- META  /data 'od-river007  /name '更新頻度  /content '不定期
|-- META  /data 'od-river007  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-river008  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-river/od-river008.html"
|-- META  /data 'od-river008  /name 'タイトル  /content '信濃川と新潟市街
|-- META  /data 'od-river008  /name 'ライセンス  /content "表示（CC-BY）"

|-- META  /data 'od-river008  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-river008  /name '公表組織名  /content '新潟市
|-- META  /data 'od-river008  /name '地域  /content '新潟市中央区下大川前通
|-- META  /data 'od-river008  /name '実効画像サイズ  /content "幅4752×高さ3168（ピクセル）"
|-- META  /data 'od-river008  /name '撮影日  /content '2014年7月30日

|-- META  /data 'od-river008  /name '撮影時刻  /content '午後1時50分
|-- META  /data 'od-river008  /name '更新頻度  /content '不定期
|-- META  /data 'od-river008  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-river009  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-river/od-river009.html"
|-- META  /data 'od-river009  /name 'タイトル  /content '信濃川と昭和大橋

|-- META  /data 'od-river009  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-river009  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-river009  /name '公表組織名  /content '新潟市
|-- META  /data 'od-river009  /name '地域  /content '新潟市中央区一番堀通町
|-- META  /data 'od-river009  /name '実効画像サイズ  /content "幅3456×高さ2304（ピクセル）"
*** 1575

|-- META  /data 'od-river009  /name '撮影日  /content '2014年6月4日
|-- META  /data 'od-river009  /name '撮影時刻  /content '午前10時7分
|-- META  /data 'od-river009  /name '更新頻度  /content '不定期
|-- META  /data 'od-river009  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-sakata001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-kata/od-sakata/od-sakata001.html"

|-- META  /data 'od-sakata001  /name 'タイトル  /content '夏の佐潟
|-- META  /data 'od-sakata001  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-sakata001  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-sakata001  /name '地域  /content '新潟市西区赤塚
|-- META  /data 'od-sakata001  /name '実効画像サイズ  /content "幅3072×高さ2048（ピクセル）"

|-- META  /data 'od-sakata001  /name '撮影日  /content '2006年8月17日
|-- META  /data 'od-sakata001  /name '撮影時間  /content '午後1時13分
|-- META  /data 'od-sakata001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-sakata002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-kata/od-sakata/od-sakata002.html"
|-- META  /data 'od-sakata002  /name 'タイトル  /content '佐潟の夕暮れ

|-- META  /data 'od-sakata002  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-sakata002  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-sakata002  /name '地域  /content '新潟市西区赤塚
|-- META  /data 'od-sakata002  /name '実効画像サイズ  /content "幅3264×高さ2448（ピクセル）"
|-- META  /data 'od-sakata002  /name '撮影日  /content '2013年11月16日

|-- META  /data 'od-sakata002  /name '撮影時間  /content '午後5時2分
|-- META  /data 'od-sakata002  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-shokuhana001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-leisure_park/od-shokuhana/od-shokuhana001.html"
|-- META  /data 'od-shokuhana001  /name 'タイトル  /content "食育・花育センター1"
|-- META  /data 'od-shokuhana001  /name 'ライセンス  /content "表示（CC-BY）"
*** 1600

|-- META  /data 'od-shokuhana001  /name '住所  /content '新潟市中央区清五郎401番地
|-- META  /data 'od-shokuhana001  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-shokuhana001  /name '公表組織名  /content '新潟市
|-- META  /data 'od-shokuhana001  /name '実効画像サイズ  /content "幅3333×高さ5014（ピクセル）"
|-- META  /data 'od-shokuhana001  /name '撮影日  /content '2012年

|-- META  /data 'od-shokuhana001  /name '更新頻度  /content '不定期
|-- META  /data 'od-shokuhana001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-shokuhana002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-leisure_park/od-shokuhana/od-shokuhana002.html"
|-- META  /data 'od-shokuhana002  /name 'タイトル  /content "食育・花育センター2"
|-- META  /data 'od-shokuhana002  /name 'ライセンス  /content "表示（CC-BY）"

|-- META  /data 'od-shokuhana002  /name '住所  /content '新潟市中央区清五郎401番地
|-- META  /data 'od-shokuhana002  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-shokuhana002  /name '公表組織名  /content '新潟市
|-- META  /data 'od-shokuhana002  /name '実効画像サイズ  /content "幅4912×高さ3264（ピクセル）"
|-- META  /data 'od-shokuhana002  /name '撮影日  /content '2011年10月4日

|-- META  /data 'od-shokuhana002  /name '撮影時刻  /content '午後3時15分
|-- META  /data 'od-shokuhana002  /name '更新頻度  /content '不定期
|-- META  /data 'od-shokuhana002  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-shokuhana003  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-shisetsu/od-leisure_park/od-shokuhana/od-shokuhana003.html"
|-- META  /data 'od-shokuhana003  /name 'タイトル  /content "食育・花育センター3"

|-- META  /data 'od-shokuhana003  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-shokuhana003  /name '住所  /content '新潟市中央区清五郎401番地
|-- META  /data 'od-shokuhana003  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-shokuhana003  /name '公表組織名  /content '新潟市
|-- META  /data 'od-shokuhana003  /name '実効画像サイズ  /content "幅4912×高さ3264（ピクセル）"
*** 1625

|-- META  /data 'od-shokuhana003  /name '撮影日  /content '2012年4月25日
|-- META  /data 'od-shokuhana003  /name '更新頻度  /content '不定期
|-- META  /data 'od-shokuhana003  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-suikeijinkou  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-toukei/od-jinkou/od-suikeijinkou.html"
|-- META  /data 'od-suikeijinkou  /name 'タイトル  /content "【推計人口】区別男女別人口及び世帯数"

|-- META  /data 'od-suikeijinkou  /name 'タグ  /content '人口
|-- META  /data 'od-suikeijinkou  /name 'ファイルサイズ  /content '3キロバイト
|-- META  /data 'od-suikeijinkou  /name 'ライセンス  /content "CC-BY（表示）"
|-- META  /data 'od-suikeijinkou  /name 'リリース日  /content '2014年12月4日
|-- META  /data 'od-suikeijinkou  /name '作成者  /content '総務部総務課

|-- META  /data 'od-suikeijinkou  /name '使用言語  /content "日本語・UTF-8"
|-- META  /data 'od-suikeijinkou  /name '公表組織名  /content '新潟市
|-- META  /data 'od-suikeijinkou  /name '更新頻度  /content '毎月
|-- META  /data 'od-suikeijinkou  /name '最終更新日  /content '2015年7月8日
|-- META  /data 'od-suikeijinkou  /name '補足1  /content "本ファイルは、平成22年10月1日現在の国勢調査結果を基に、出生・死亡・転入・転出等を加減した現在の推計人口です。"

|-- META  /data 'od-suikeijinkou  /name '補足2  /content "最新版は、平成27年6月1日現在の数値です。"
|-- META  /data 'od-suikeijinkou  /name '補足3  /content "本ファイルには、年齢別数値の掲載はありません。"
|-- META  /data 'od-toyanogata001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-kata/od-toyanogata/od-toyanogata001.html"
|-- META  /data 'od-toyanogata001  /name 'タイトル  /content '鳥屋野潟と朝日
|-- META  /data 'od-toyanogata001  /name 'ライセンス  /content "表示（CC-BY）"

|-- META  /data 'od-toyanogata001  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-toyanogata001  /name '地域  /content '新潟市中央区
|-- META  /data 'od-toyanogata001  /name '実効画像サイズ  /content "幅4608×高さ3456（ピクセル）"
|-- META  /data 'od-toyanogata001  /name '撮影日  /content '2013年11月23日
|-- META  /data 'od-toyanogata001  /name '撮影時間  /content '午前6時59分
*** 1650

|-- META  /data 'od-toyanogata001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-toyanogata002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-kata/od-toyanogata/od-toyanogata002.html"
|-- META  /data 'od-toyanogata002  /name 'タイトル  /content '鳥屋野潟と新潟市街
|-- META  /data 'od-toyanogata002  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-toyanogata002  /name "公表者・作成者"  /content "地域・魅力創造部広報課"

|-- META  /data 'od-toyanogata002  /name '地域  /content '新潟市中央区
|-- META  /data 'od-toyanogata002  /name '実効画像サイズ  /content "幅5184×高さ3456（ピクセル）"
|-- META  /data 'od-toyanogata002  /name '撮影日  /content '2013年5月8日
|-- META  /data 'od-toyanogata002  /name '撮影時間  /content '午前11時1分
|-- META  /data 'od-toyanogata002  /name "言語・文字コード"  /content "日本語・UTF-8"

|-- META  /data 'od-uwasekigata001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-kata/od-uwasekigata/od-uwasekigata001.html"
|-- META  /data 'od-uwasekigata001  /name 'タイトル  /content '初秋の上堰潟1
|-- META  /data 'od-uwasekigata001  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-uwasekigata001  /name '作成者  /content "地域・魅力創造部広報課"
|-- META  /data 'od-uwasekigata001  /name '公表組織名  /content '新潟市

|-- META  /data 'od-uwasekigata001  /name '地域  /content '新潟市西蒲区松野尾
|-- META  /data 'od-uwasekigata001  /name '実効画像サイズ  /content "幅3072×高さ2304（ピクセル）"
|-- META  /data 'od-uwasekigata001  /name '撮影日  /content '2013年9月6日
|-- META  /data 'od-uwasekigata001  /name '撮影時刻  /content '午後3時55分
|-- META  /data 'od-uwasekigata001  /name '更新頻度  /content '不定期

|-- META  /data 'od-uwasekigata001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-uwasekigata002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-kata/od-uwasekigata/od-uwasekigata002.html"
|-- META  /data 'od-uwasekigata002  /name 'タイトル  /content '初秋の上堰潟2
|-- META  /data 'od-uwasekigata002  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-uwasekigata002  /name '作成者  /content "地域・魅力創造部広報課"
*** 1675

|-- META  /data 'od-uwasekigata002  /name '公表組織名  /content '新潟市
|-- META  /data 'od-uwasekigata002  /name '地域  /content '新潟市西蒲区松野尾
|-- META  /data 'od-uwasekigata002  /name '実効画像サイズ  /content "幅3264×高さ2448（ピクセル）"
|-- META  /data 'od-uwasekigata002  /name '撮影日  /content '2013年9月6日
|-- META  /data 'od-uwasekigata002  /name '撮影時刻  /content '午後3時55分

|-- META  /data 'od-uwasekigata002  /name '更新頻度  /content '不定期
|-- META  /data 'od-uwasekigata002  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-yuuhi001  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-yuuhi/od-yuuhi001.html"
|-- META  /data 'od-yuuhi001  /name 'タイトル  /content '角田山の夕景1
|-- META  /data 'od-yuuhi001  /name 'ライセンス  /content "表示（CC-BY）"

|-- META  /data 'od-yuuhi001  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-yuuhi001  /name '地域  /content '新潟市西蒲区
|-- META  /data 'od-yuuhi001  /name '実効画像サイズ  /content "幅4256×高さ2832（ピクセル）"
|-- META  /data 'od-yuuhi001  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-yuuhi002  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-yuuhi/od-yuuhi002.html"

|-- META  /data 'od-yuuhi002  /name 'タイトル  /content '角田山の夕景2
|-- META  /data 'od-yuuhi002  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-yuuhi002  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-yuuhi002  /name '地域  /content '新潟市西蒲区
|-- META  /data 'od-yuuhi002  /name '実効画像サイズ  /content "幅3648×高さ2427（ピクセル）"

|-- META  /data 'od-yuuhi002  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-yuuhi003  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-yuuhi/od-yuuhi003.html"
|-- META  /data 'od-yuuhi003  /name 'タイトル  /content '日本海夕日ライン
|-- META  /data 'od-yuuhi003  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-yuuhi003  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
*** 1700

|-- META  /data 'od-yuuhi003  /name '地域  /content '新潟市西蒲区
|-- META  /data 'od-yuuhi003  /name '実効画像サイズ  /content "幅5616×高さ3744（ピクセル）"
|-- META  /data 'od-yuuhi003  /name "言語・文字コード"  /content "日本語・UTF-8"
|-- META  /data 'od-yuuhi004  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-gazou/od-fukei/od-yuuhi/od-yuuhi004.html"
|-- META  /data 'od-yuuhi004  /name 'タイトル  /content '夕日に染まる山の下海浜公園

|-- META  /data 'od-yuuhi004  /name 'ライセンス  /content "表示（CC-BY）"
|-- META  /data 'od-yuuhi004  /name "公表者・作成者"  /content "地域・魅力創造部広報課"
|-- META  /data 'od-yuuhi004  /name '地域  /content '新潟市東区船江町
|-- META  /data 'od-yuuhi004  /name '実効画像サイズ  /content "幅4313×高さ2850（ピクセル）"
|-- META  /data 'od-yuuhi004  /name "言語・文字コード"  /content "日本語・UTF-8"

|-- META  /data 'od-zei_syoumei_mado  /name 'URL  /content "http://www.city.niigata.lg.jp/shisei/seisaku/it/open-data/opendata-tetsuduki/od-zei_syoumei_mado.html"
|-- META  /data 'od-zei_syoumei_mado  /name 'タイトル  /content '税系証明発行窓口一覧
|-- META  /data 'od-zei_syoumei_mado  /name 'タグ  /content "くらし、手続き"
|-- META  /data 'od-zei_syoumei_mado  /name 'ファイルサイズ  /content '12キロバイト
|-- META  /data 'od-zei_syoumei_mado  /name 'ライセンス  /content "CC-BY（表示）"

|-- META  /data 'od-zei_syoumei_mado  /name 'リリース日  /content '2015年4月30日
|-- META  /data 'od-zei_syoumei_mado  /name '作成者  /content '市税事務所市民税課
|-- META  /data 'od-zei_syoumei_mado  /name '使用言語  /content "日本語・UTF-8"
|-- META  /data 'od-zei_syoumei_mado  /name '公表者  /content '総務部IT推進課
|-- META  /data 'od-zei_syoumei_mado  /name '更新頻度  /content '随時

|-- META  /data 'od-zei_syoumei_mado  /name '最終更新日  /content '2015年4月30日
|-- META  /data 'od-zei_syoumei_mado  /name '組織名  /content '新潟市

*** 1722 judges

**
**  SUMMARY
**    1722 judges on META
**    1722 judges in total
**
