** -*- koshu -*-
**
**  INPUT
**    ../../../open-data/gazou/gazou.k
**    license-calc.k
**
**  OUTPUT
**    license-data.k
**

=== license

  このデータセットは以下の著作物を改変して作成しています。
  新潟市オープンデータ、新潟市、クリエイティブ・コモンズ・ライセンス 表示 2.1 日本
  (CC-BY 2.1 JP) http://creativecommons.org/licenses/by/2.1/jp/

=== rel

|-- ライセンス  /ライセンス '表示  /データ数 92

*** 1 judge 

**
**  SUMMARY
**       1 judge  on ライセンス
**       1 judge  in total
**
