** -*- koshu -*-
**
**  新潟市オープンデータを甲州記法へ変換したファイルの一覧です。
**  このファイルは 'convert.sh' によって生成されました。
**

=== license

  このデータセットは以下の著作物を改変して作成しています。
  新潟市オープンデータ、新潟市、クリエイティブ・コモンズ・ライセンス 表示 2.1 日本
  (CC-BY 2.1 JP) http://creativecommons.org/licenses/by/2.1/jp/

=== rel

|-- CONVERT-LOG  /process 'skip  /csv-lines 65  /path "opendata-gis/od-gis_dourosuido/od-gis_gesuido.files/od_gis_103_gesuido.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 6893  /path "opendata-gis/od-gis_dourosuido/od-gis_hojoten.files/od_gis_196_hojoten.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 387  /path "opendata-gis/od-gis_dourosuido/od-gis_kendo_hashi.files/od_gis_258_kendo_hashi.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 129  /path "opendata-gis/od-gis_dourosuido/od-gis_kokudo_hashi.files/od_gis_257_kokudo_hashi.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 304  /path "opendata-gis/od-gis_dourosuido/od-gis_sankakuten.files/od_gis_192_gaiku_sankakuten.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 129  /path "opendata-gis/od-gis_dourosuido/od-gis_sankakuten_np.files/od_gis_193_gaiku_sankakuten_setten.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 3567  /path "opendata-gis/od-gis_dourosuido/od-gis_shido_hashi.files/od_gis_259_shido_hashi.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 2068  /path "opendata-gis/od-gis_dourosuido/od-gis_takakuten.files/od_gis_194_gaiku_takakuten.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 1998  /path "opendata-gis/od-gis_dourosuido/od-gis_takakuten_np.files/od_gis_195_gaiku_takakuten_setten.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 27  /path "opendata-gis/od-gis_dourosuido/od-gis_waterworksins.files/od_gis_102_waterworksinstitution.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 19  /path "opendata-gis/od-gis_kankobunspo/od-gis_bus_hakusan.files/od_gis_79_junkanbus_hakusan.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 107  /path "opendata-gis/od-gis_kankobunspo/od-gis_greenandblue.files/od_gis_121_greenandbluetourism.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 19  /path "opendata-gis/od-gis_kankobunspo/od-gis_inuyashago.files/od_gis_78_junkanbus_inuyasha.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 744  /path "opendata-gis/od-gis_kankobunspo/od-gis_iseki.files/od_gis_113_iseki.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 25  /path "opendata-gis/od-gis_kankobunspo/od-gis_onseninst.files/od_gis_80_onseninstitution.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 81  /path "opendata-gis/od-gis_kankobunspo/od-gis_pkbicycles.files/od_gis_77_pkbicycles.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 26  /path "opendata-gis/od-gis_kankobunspo/od-gis_rentcycle.files/od_gis_76_rentcycle.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 17  /path "opendata-gis/od-gis_kankobunspo/od-gis_shiminnoen.files/od_gis_71_shiminnoen.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 98  /path "opendata-gis/od-gis_kankobunspo/od-gis_sports.files/od_gis_56_sports.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 52  /path "opendata-gis/od-gis_kankobunspo/od-gis_wifi.files/od-gis_wi-fi.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 397  /path "opendata-gis/od-gis_kenkofukushi/od-gis_aed.files/od_gis_151_aed.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 2  /path "opendata-gis/od-gis_kenkofukushi/od-gis_eiseikankyo.files/od_gis_110_eiseikankyo.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 125  /path "opendata-gis/od-gis_kenkofukushi/od-gis_forshogaisha.files/od_gis_106_forshogaishashisetsu.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 223  /path "opendata-gis/od-gis_kenkofukushi/od-gis_hoikuen.files/od_gis_107_hoikuen.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 26  /path "opendata-gis/od-gis_kenkofukushi/od-gis_hokenfukushi.files/od_gis_108_hokenfukushi.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 5  /path "opendata-gis/od-gis_kenkofukushi/od-gis_hokenjo.files/od_gis_109_hokenjo.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 199  /path "opendata-gis/od-gis_kenkofukushi/od-gis_kenko_ben.files/od_gis_190_kenkodukuri_bento.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 226  /path "opendata-gis/od-gis_kenkofukushi/od-gis_kenko_in.files/od_gis_189_kenkodukuri_inshoku.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 18  /path "opendata-gis/od-gis_kenkofukushi/od-gis_kenko_kyu.files/od_gis_553_kenkodukuri_kyushoku.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 2  /path "opendata-gis/od-gis_kenkofukushi/od-gis_shokuniku.files/od_gis_181_shokunikukensa.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 63  /path "opendata-gis/od-gis_kosodate/od-gis_chugakko.files/od_gis_86_chugakko.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 47  /path "opendata-gis/od-gis_kosodate/od-gis_community.files/od_gis_98_communitycenter.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 62  /path "opendata-gis/od-gis_kosodate/od-gis_communitycent.files/od_gis_100_communitycenter_etc.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 132  /path "opendata-gis/od-gis_kosodate/od-gis_himawari.files/od_gis_57_himawari.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 19  /path "opendata-gis/od-gis_kosodate/od-gis_jidocenter.files/od_gis_58_jidocenter.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 46  /path "opendata-gis/od-gis_kosodate/od-gis_library.files/od_gis_94_library.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 26  /path "opendata-gis/od-gis_kosodate/od-gis_shiminkaikan.files/od_gis_99_shiminkaikan.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 116  /path "opendata-gis/od-gis_kosodate/od-gis_shogakko.files/od_gis_85_shogakko.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 54  /path "opendata-gis/od-gis_kosodate/od-gis_yochien.files/od_gis_84_yochien.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 24  /path "opendata-gis/od-gis_kurashibosai/od-gis_asaichi.files/od_gis_114_asaichi.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 154  /path "opendata-gis/od-gis_kurashibosai/od-gis_chisan_inshok.files/od_gis_153_chisan_inshoku.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 70  /path "opendata-gis/od-gis_kurashibosai/od-gis_chisan_kouri.files/od_gis_152_chisan_kouri.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 4  /path "opendata-gis/od-gis_kurashibosai/od-gis_dobokujimusho.files/od_gis_123_dobokujimusho_etc.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 79  /path "opendata-gis/od-gis_kurashibosai/od-gis_farmstand.files/od_gis_115_farmstand.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 6  /path "opendata-gis/od-gis_kurashibosai/od-gis_fishingbase.files/od_gis_116_fishingbase.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 220  /path "opendata-gis/od-gis_kurashibosai/od-gis_okugaihinan.files/od_gis_83_okugaihinanbasho.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 368  /path "opendata-gis/od-gis_kurashibosai/od-gis_okunaihinanjo.files/od_gis_82_okunaihinanjo.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 1572  /path "opendata-gis/od-gis_kurashibosai/od-gis_park.files/od_gis_59_park.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 255  /path "opendata-gis/od-gis_kurashibosai/od-gis_shieijutaku.files/od_gis_75_shieijutaku.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 39  /path "opendata-gis/od-gis_kurashibosai/od-gis_shiyakusho.files/od_gis_137_shiyakusho_etc.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 39  /path "opendata-gis/od-gis_kurashibosai/od-gis_shobo.files/od_gis_81_shobo.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 22  /path "opendata-gis/od-gis_kurashibosai/od-gis_wtf.files/od_gis_101_wtf.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 49  /path "opendata-tetsuduki/od-juki_syoumei_mado.files/od-juki_syoumei_mado.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 49  /path "opendata-tetsuduki/od-juki_todoke_mado.files/od-juki_todoke_mado.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 51  /path "opendata-tetsuduki/od-zei_syoumei_mado.files/od-zei_syoumei_mado.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 13  /path "opendata-toukei/od-jinkou/od-suikeijinkou.files/2011suikeijinkou.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 13  /path "opendata-toukei/od-jinkou/od-suikeijinkou.files/2012suikeijinkou.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 13  /path "opendata-toukei/od-jinkou/od-suikeijinkou.files/2013suikeijinkou.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 13  /path "opendata-toukei/od-jinkou/od-suikeijinkou.files/2014suikeijinkou.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 13  /path "opendata-toukei/od-jinkou/od-suikeijinkou.files/2015suikeijinkou.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 45  /path "opendata-toukei/od-kankyo/od-mizukankyo/od-mizu.files/H25suishitsu.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 12  /path "opendata-toukei/od-kankyo/od-ondanka/od-energy.files/biomass.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 12  /path "opendata-toukei/od-kankyo/od-ondanka/od-energy.files/EVshisetsu.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 2  /path "opendata-toukei/od-kankyo/od-ondanka/od-energy.files/gesuiodei.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 5  /path "opendata-toukei/od-kankyo/od-ondanka/od-energy.files/gomienergy.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 4  /path "opendata-toukei/od-kankyo/od-ondanka/od-energy.files/gomihatuden.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 30  /path "opendata-toukei/od-kankyo/od-ondanka/od-energy.files/hybridgaito.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 7  /path "opendata-toukei/od-kankyo/od-ondanka/od-energy.files/pvgaito.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 42  /path "opendata-toukei/od-kankyo/od-ondanka/od-energy.files/pvshisetsu.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 7  /path "opendata-toukei/od-kankyo/od-ondanka/od-energy.files/sonota.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 33  /path "opendata-toukei/od-kankyo/od-otokankyo/od-oto.files/H25oto.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 98  /path "opendata-toukei/od-kankyo/od-shizenkankyo/od-bird.files/sagatabird.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 83  /path "opendata-toukei/od-kankyo/od-shizenkankyo/od-bird.files/toyanobird.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 104  /path "opendata-toukei/od-kokucho/od-h17kokuchou/od-h17kokuchonenrei.files/H17kokuchonenrei.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 10  /path "opendata-toukei/od-kokucho/od-h17kokuchou/od-h17kokuchosetai.files/H17kokuchosetai.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 20  /path "opendata-toukei/od-kokucho/od-h17kokuchou/od-h17kokuchosyugyo.files/H17kokuchosyugyo.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 104  /path "opendata-toukei/od-kokucho/od-h22kokuchou/od-h22kokuchonenrei.files/H22kokuchonenrei.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 10  /path "opendata-toukei/od-kokucho/od-h22kokuchou/od-h22kokuchosetai.files/H22kokuchosetai.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 22  /path "opendata-toukei/od-kokucho/od-h22kokuchou/od-h22kokuchosyugyo.files/H22kokuchosyugyo.csv"

**
**  件数
**    convert  13
**    skip     66
**    合計     79
**
