** -*- koshu -*-
**
**  新潟市オープンデータを甲州記法へ変換したファイルの一覧です。
**  このファイルは 'convert.sh' によって生成されました。
**

=== license

  このデータセットは以下の著作物を改変して作成しています。
  新潟市オープンデータ、新潟市、クリエイティブ・コモンズ・ライセンス 表示 2.1 日本
  (CC-BY 2.1 JP) http://creativecommons.org/licenses/by/2.1/jp/

=== rel

|-- CONVERT-LOG  /process 'convert  /csv-lines 65  /path "opendata-gis/od-gis_dourosuido/od-gis_gesuido.files/od_gis_103_gesuido.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 6893  /path "opendata-gis/od-gis_dourosuido/od-gis_hojoten.files/od_gis_10145_hojoten.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 387  /path "opendata-gis/od-gis_dourosuido/od-gis_kendo_hashi.files/od_gis_10132_kendo_hashi.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 129  /path "opendata-gis/od-gis_dourosuido/od-gis_kokudo_hashi.files/od_gis_10131_kokudo_hashi.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 304  /path "opendata-gis/od-gis_dourosuido/od-gis_sankakuten.files/od_gis_10141_gaiku_sankakuten.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 129  /path "opendata-gis/od-gis_dourosuido/od-gis_sankakuten_np.files/od_gis_10142_gaiku_sankakuten_setten.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 3567  /path "opendata-gis/od-gis_dourosuido/od-gis_shido_hashi.files/od_gis_10133_shido_hashi.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 2068  /path "opendata-gis/od-gis_dourosuido/od-gis_takakuten.files/od_gis_10143_gaiku_takakuten.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 1998  /path "opendata-gis/od-gis_dourosuido/od-gis_takakuten_np.files/od_gis_10144_gaiku_takakuten_setten.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 27  /path "opendata-gis/od-gis_dourosuido/od-gis_waterworksins.files/od_gis_10151_waterworksinstitution.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 19  /path "opendata-gis/od-gis_kankobunspo/od-gis_bus_hakusan.files/od_gis_10095_junkanbus_hakusan.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 107  /path "opendata-gis/od-gis_kankobunspo/od-gis_greenandblue.files/od_gis_10098_greenandbluetourism.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 744  /path "opendata-gis/od-gis_kankobunspo/od-gis_iseki.files/od_gis_10115_iseki.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 25  /path "opendata-gis/od-gis_kankobunspo/od-gis_onseninst.files/od_gis_10096_onseninstitution.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 81  /path "opendata-gis/od-gis_kankobunspo/od-gis_pkbicycles.files/od_gis_10093_pkbicycles.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 26  /path "opendata-gis/od-gis_kankobunspo/od-gis_rentcycle.files/od_gis_10092_rentcycle.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 17  /path "opendata-gis/od-gis_kankobunspo/od-gis_shiminnoen.files/od_gis_10091_shiminnoen.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 98  /path "opendata-gis/od-gis_kankobunspo/od-gis_sports.files/od_gis_10111_sports.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 19  /path "opendata-gis/od-gis_kankobunspo/od-gis_tokimesse.files/od_gis_10094_junkanbus_tokimesse.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 52  /path "opendata-gis/od-gis_kankobunspo/od-gis_wifi.files/od_gis_10099_wifi.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 436  /path "opendata-gis/od-gis_kenkofukushi/od-gis_aed.files/od_gis_10061_aed.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 2  /path "opendata-gis/od-gis_kenkofukushi/od-gis_eiseikankyo.files/od_gis_10067_eiseikankyo.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 125  /path "opendata-gis/od-gis_kenkofukushi/od-gis_forshogaisha.files/od_gis_10081_forshogaishashisetsu.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 223  /path "opendata-gis/od-gis_kenkofukushi/od-gis_hoikuen.files/od_gis_107_hoikuen.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 26  /path "opendata-gis/od-gis_kenkofukushi/od-gis_hokenfukushi.files/od_gis_10082_hokenfukushi.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 5  /path "opendata-gis/od-gis_kenkofukushi/od-gis_hokenjo.files/od_gis_10065_hokenjo.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 199  /path "opendata-gis/od-gis_kenkofukushi/od-gis_kenko_ben.files/od_gis_10063_kenkodukuri_bento.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 226  /path "opendata-gis/od-gis_kenkofukushi/od-gis_kenko_in.files/od_gis_10062_kenkodukuri_inshoku.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 18  /path "opendata-gis/od-gis_kenkofukushi/od-gis_kenko_kyu.files/od_gis_10064_kenkodukuri_kyushoku.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 2  /path "opendata-gis/od-gis_kenkofukushi/od-gis_shokuniku.files/od_gis_10066_shokunikukensa.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 63  /path "opendata-gis/od-gis_kosodate/od-gis_chugakko.files/od_gis_10034_chugakko.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 47  /path "opendata-gis/od-gis_kosodate/od-gis_community.files/od_gis_10052_communitycenter.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 62  /path "opendata-gis/od-gis_kosodate/od-gis_communitycent.files/od_gis_10054_communitycenter_etc.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 19  /path "opendata-gis/od-gis_kosodate/od-gis_jidocenter.files/od_gis_10042_jidocenter.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 132  /path "opendata-gis/od-gis_kosodate/od-gis_jidoclub.files/od_gis_10041_jidoclub.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 45  /path "opendata-gis/od-gis_kosodate/od-gis_library.files/od_gis_10051_library.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 26  /path "opendata-gis/od-gis_kosodate/od-gis_shiminkaikan.files/od_gis_10053_shiminkaikan.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 116  /path "opendata-gis/od-gis_kosodate/od-gis_shogakko.files/od_gis_10033_shogakko.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 54  /path "opendata-gis/od-gis_kosodate/od-gis_yochien.files/od_gis_84_yochien.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 24  /path "opendata-gis/od-gis_kurashibosai/od-gis_asaichi.files/od_gis_10013_asaichi.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 154  /path "opendata-gis/od-gis_kurashibosai/od-gis_chisan_inshok.files/od_gis_10017_chisan_inshoku.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 70  /path "opendata-gis/od-gis_kurashibosai/od-gis_chisan_kouri.files/od_gis_10016_chisan_kouri.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 4  /path "opendata-gis/od-gis_kurashibosai/od-gis_dobokujimusho.files/od_gis_10002_dobokujimusho_etc.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 79  /path "opendata-gis/od-gis_kurashibosai/od-gis_farmstand.files/od_gis_10014_farmstand.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 6  /path "opendata-gis/od-gis_kurashibosai/od-gis_fishingbase.files/od_gis_10015_fishingbase.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 220  /path "opendata-gis/od-gis_kurashibosai/od-gis_okugaihinan.files/od_gis_10162_okugaihinanbasho.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 368  /path "opendata-gis/od-gis_kurashibosai/od-gis_okunaihinanjo.files/od_gis_10161_okunaihinanjo.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 1570  /path "opendata-gis/od-gis_kurashibosai/od-gis_park.files/od_gis_10019_park.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 255  /path "opendata-gis/od-gis_kurashibosai/od-gis_shieijutaku.files/od_gis_10012_shieijutaku.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 39  /path "opendata-gis/od-gis_kurashibosai/od-gis_shiyakusho.files/od_gis_10001_shiyakusho_etc.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 39  /path "opendata-gis/od-gis_kurashibosai/od-gis_shobo.files/od_gis_10003_shobo.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 22  /path "opendata-gis/od-gis_kurashibosai/od-gis_wtf.files/od_gis_10011_wtf.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 49  /path "opendata-tetsuduki/od-juki_syoumei_mado.files/od-juki_syoumei_mado.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 49  /path "opendata-tetsuduki/od-juki_todoke_mado.files/od-juki_todoke_mado.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 51  /path "opendata-tetsuduki/od-zei_syoumei_mado.files/od-zei_syoumei_mado.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 13  /path "opendata-toukei/od-jinkou/od-suikeijinkou.files/2011suikeijinkou.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 13  /path "opendata-toukei/od-jinkou/od-suikeijinkou.files/2012suikeijinkou.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 13  /path "opendata-toukei/od-jinkou/od-suikeijinkou.files/2013suikeijinkou.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 13  /path "opendata-toukei/od-jinkou/od-suikeijinkou.files/2014suikeijinkou.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 13  /path "opendata-toukei/od-jinkou/od-suikeijinkou.files/2015suikeijinkou.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 45  /path "opendata-toukei/od-kankyo/od-mizukankyo/od-mizu.files/H25suishitsu.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 12  /path "opendata-toukei/od-kankyo/od-ondanka/od-energy.files/biomass.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 12  /path "opendata-toukei/od-kankyo/od-ondanka/od-energy.files/EVshisetsu.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 2  /path "opendata-toukei/od-kankyo/od-ondanka/od-energy.files/gesuiodei.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 5  /path "opendata-toukei/od-kankyo/od-ondanka/od-energy.files/gomienergy.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 4  /path "opendata-toukei/od-kankyo/od-ondanka/od-energy.files/gomihatuden.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 30  /path "opendata-toukei/od-kankyo/od-ondanka/od-energy.files/hybridgaito.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 7  /path "opendata-toukei/od-kankyo/od-ondanka/od-energy.files/pvgaito.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 42  /path "opendata-toukei/od-kankyo/od-ondanka/od-energy.files/pvshisetsu.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 7  /path "opendata-toukei/od-kankyo/od-ondanka/od-energy.files/sonota.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 33  /path "opendata-toukei/od-kankyo/od-otokankyo/od-oto.files/H25oto.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 98  /path "opendata-toukei/od-kankyo/od-shizenkankyo/od-bird.files/sagatabird.csv"
|-- CONVERT-LOG  /process 'convert  /csv-lines 83  /path "opendata-toukei/od-kankyo/od-shizenkankyo/od-bird.files/toyanobird.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 104  /path "opendata-toukei/od-kokucho/od-h17kokuchou/od-h17kokuchonenrei.files/H17kokuchonenrei.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 10  /path "opendata-toukei/od-kokucho/od-h17kokuchou/od-h17kokuchosetai.files/H17kokuchosetai.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 20  /path "opendata-toukei/od-kokucho/od-h17kokuchou/od-h17kokuchosyugyo.files/H17kokuchosyugyo.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 104  /path "opendata-toukei/od-kokucho/od-h22kokuchou/od-h22kokuchonenrei.files/H22kokuchonenrei.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 10  /path "opendata-toukei/od-kokucho/od-h22kokuchou/od-h22kokuchosetai.files/H22kokuchosetai.csv"
|-- CONVERT-LOG  /process 'skip  /csv-lines 22  /path "opendata-toukei/od-kokucho/od-h22kokuchou/od-h22kokuchosyugyo.files/H22kokuchosyugyo.csv"

**
**  件数
**    convert  15
**    skip     64
**    合計     79
**
